### ISSUE TITLE
Presets (prefabs?) for the easy re-initialization of an entity pattern

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#104]
As the old `README.md` stated, we might want to:
```
Presets (prefabs?) for the easy re-initialization of an entity pattern
```

I'm not sure what's wrong with the current implementation, or what we'd want to change. 

If @paked could clarify, or close this issue, that'd be great.

**Comment by paked** [comment]
@EtienneBruines Unity has a system where one can create an `Entity` and the re initialise it multiple times into new entities. I think a similar system would be pretty cool. I imagine something liek

```go
e := NewEntity([]string{"RenderSystem"}) // Create template entity
// do things to entity

es := e.Duplicate(20) // fill a group with 20 different e's

w.Add(es)
```

This should be added after groups.

**Comment by EtienneBruines** [comment]
As groups is something the user should probably implement himself, we could allow this:

```go
e := NewEntity([]string{"RenderSystem"}) // Create template entity
// do things to entity

es := e.Duplicate(20) // fill a group with 20 different e's

w.Add(es...)
```

Where the `Duplicate` function indeed duplicates the `Entity`s and all `Component`s? Is that something you'd like to see, @paked?

**Comment by EtienneBruines** [comment]
Closed this. Discussion/development should continue at https://github.com/EngoEngine/ecs/issues/5
