### ISSUE TITLE
Legacy drawing

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#131]
Do we want any of these? (edit if we come up with more)

------

Draw: 
* [x] Circle
* [x] Polygon
    * [x] Triangle
    * [x] Rectangle
* [x] Line
    * [ ] Dotted line

Options:
* [x] Size (obviously)
* [x] Line width
* [x] Line color
* [x] Fill color 
* [x] Border (+color? ) - don't know if this can be done

TODO:
* [x] Find out if we want this by using `Shader`s, or `Texture`s.

**Comment by matiwinnetou** [comment]
Isn't that usually a low level graphics driver offers such features? Since I suppose we want to abstract a graphics driver then it would make sense to expose some sort of bridge interfaces for these shapes.

**Comment by EtienneBruines** [comment]
Well, I haven't seen any easy `OpenGL` functions one could use; so I think it's up to us.

**Comment by EtienneBruines** [comment]
We should wait until we have #155 merged, that way we can work with matrices in our shaders. We'll need them.

**Comment by EtienneBruines** [comment]
I am going to skip the circle for now. Looks like OpenGL doesn't like circles.

**Comment by EtienneBruines** [comment]
Time for some discussion. Looks like some things are going to be tricky overall:

* Circles / Dotted-line (hard, but possible)
* Line color (as OpenGL only has "fill")
* Border

The main problem is defining them within a `RenderComponent`. Basically they'd have to be some kind of `Drawable`. 

```go

type Drawable interface {
	Texture() *gl.Texture
	Width() float32
	Height() float32
	View() (float32, float32, float32, float32)
	Close()
}
```

All these values would return default values for all basic shapes. We would do a type-switch (like we do with the Systems) -- this way we'd know it's a Triangle / Line / etc., and know we should ignore the `gl.Texture` (it's `nil` anyway). 

## Draft: 

```go

type Triangle struct {}

func (*Triangle) Texture() *gl.Texture                       { return nil }
func (*Triangle) Width() float32                             { return 0 }
func (*Triangle) Height() float32                            { return 0 }
func (*Triangle) View() (float32, float32, float32, float32) { return 0, 0, 1, 1 }
func (*Triangle) Close()                                     {}
```

**Comment by EtienneBruines** [comment]
Done in #266
