### ISSUE TITLE
Resize Font

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#137]
Some aspects of the game, may be resized whenever the game window is resized. 

Text / Font is usually *not* one of those things that should be resized. At least not on just one axis, but with the aspect ratio in place. 

Perhaps other things should also be resized with aspect ratio preserved?

**Comment by EtienneBruines** [comment]
Is this something we should let the user/programmer handle? Because resizing with aspect ratio preserved isn't something we can do (we can resize it, but how would we move / align it?

**Comment by paked** [comment]
I think this is something we should leave to the user.
