### ISSUE TITLE
Fix examples

### ISSUE THREAD

**Issue by paked** [EngoEngine/engo#14]
It seems like the examples are broken from when better font support was added.

* [x] Pong
* [x] botmark.go
* [x] game.go
* [x] hello.go
* [ ] tilemap.go

**Comment by EtienneBruines** [comment]
This commit https://github.com/paked/engi/commit/ff424f9414d2355bde697560f86831863f0f2e47 seems to be (partially) to blame. Referencing because it shows old behavior with the Fonts.

**Comment by paked** [comment]
@EtienneBruines yes, I believe the problem is that we never got around to updating the examples when we made an API change (d'oh!). It is not necessarily a bug as such, as a working updated example can be found [here](https://github.com/Newbrict/OakTale).

**Comment by EtienneBruines** [comment]
Looks like the font now sees https://github.com/paked/engi/blob/master/demos/pong/assets/font.png as a bad ttf file.

**Comment by EtienneBruines** [comment]
Note that the example `falling.go` has a `DeathSystem` that listens for `ScoreMessage`s, but they are not defined, nor sent.

**Comment by paked** [comment]
@EtienneBruines Was this fixed in your latest PR?

**Comment by EtienneBruines** [comment]
As it wasn't a compiler-error, no, it wasn't. I wasn't sure at which point it should send `ScoreMessage`s.

**Comment by paked** [comment]
@EtienneBruines makes sense. I'll add this to my TODO list.

**Comment by paked** [comment]
Regarding this. I believe we can drop the `botmark` demo. It was a benchmark, and those are being worked on in #40

**Comment by EtienneBruines** [comment]
:thumbsup:

**Comment by EtienneBruines** [comment]
This is being continued on #161 and #162. 

Closing this issue as it does not contribute anything further.
