### ISSUE TITLE
package issues on windows

### ISSUE THREAD

**Issue by varomix** [EngoEngine/engo#140]
Hey guys
I'm trying to test the engine
I'm getting this issue when getting the source

```go
 go get -u github.com/paked/engi
package golang.org/x/mobile/exp/audio/al: no buildable Go source files in C:\media\PROJECTx\mixgo\src\golang.org\x\mobile\exp\audio\al
```

I'm new to Go so not sure what the issue is, I'm using windows 10 64bit

thanks

**Comment by EtienneBruines** [comment]
Hey varomix. The issue means that we (those that are programming on `engi`), made a mistake with the Windows audio support. Roughly, the error message means that the audio library we're using (golang.org/x/mobile/exp/audio/al) hasn't got code that will compile on Windows. 

We tried fixing that, but apparently we failed. Let me give it another shot.

**Comment by EtienneBruines** [comment]
Apparently #141 did not fix the issue. Will have to try and see if I get it running on my Windows pc.

**Comment by cryptrol** [comment]
Your put a conditional compilation tag to avoid compiling in Windows, but in order for it to work you should put a new line between the tag and the package line. Like this :

```
// +build !windows

package engi

**Comment by EtienneBruines** [comment]
I seriously forgot that? Shame on me. 

Thank you @cryptrol for noticing that.

**Comment by cryptrol** [comment]
I just lost some hours once because of this. Conditional compilation is always a pain :laughing: 

`go vet` helps finding it.

**Comment by varomix** [comment]
@EtienneBruines I just made the change locally in the audio.go file and I STILL get the same issue :)
btw I'm using Atom editor with the Go-Plus package and it reports all that formatting stuff every time you save is really cool, I opened the audio.go file in atom and told me about the black line :)

so, it's still not working, is there any other files that need to be modified? 
I got it to work on linux :)

Thanks

**Comment by varomix** [comment]
I added the compile flag to audio.go and audio_player.go  and the error was gone but there's more issues

```  go
 go run entity.go
# github.com/paked/engi
..\..\assets.go:83: undefined: ReadSeekCloser
..\..\audio_windows.go:18: undefined: Player
```

**Comment by 5k3105** [comment]
Still doesn't work on windows. Same error as at the start of this thread.

**Comment by EtienneBruines** [comment]
You're completely right. I haven't given this issue the attention it deserved. 

Creating a virtual Windows environment atm (so test in Windows, but develop in Linux)

**Comment by EtienneBruines** [comment]
I managed to compile and run it on my virtual Windows using #168. 

However, my setup doesn't support OpenGL within virtualbox. 

Could anyone verify it actually runs like it should?

**Comment by paked** [comment]
Keeping this open, as we do not know whether it *actually* works

**Comment by 5k3105** [comment]
```
λ go get github.com/paked/engi
# github.com/go-gl/glfw/v3.1/glfw
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
# github.com/go-gl/gl/v2.1/gl
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
```
I'm using TDM 64 bit. Should this be something else?

**Comment by EtienneBruines** [comment]
I was using [win-builds](http://win-builds.org/doku.php) and downloaded everything available, which included the GCC-compiler and a lot of other stuff (92 packages in total). 

Not sure if that solves your problem? (not that used to the windows-way of compiling/linking stuff)

**Comment by 5k3105** [comment]
Awesome! Everything seems to work now (except audio). I tested all the demos. Path set to C:\Program Files\WinBuilds

Thanks Etienne!

**Comment by EtienneBruines** [comment]
Created #174 and #175 to continue on those separate issues. 

Closing this issue as the compilation-part (and thus the package issues) has been fixed.
