### ISSUE TITLE
AudioSystem volume

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#147]
It would be nice to have categories of audio fragments, and to be able to set the volume (loudness) for each of those categories, i.e. a category for ambiance, effects, voice, etc. These categories should be user-defined. 

We could also offer a master-volume.

**Comment by paked** [comment]
:+1: 

I might start hacking on this once I have a proper setup again :angry:

**Comment by paked** [comment]
I'm going to take this!
