### ISSUE TITLE
PriorityLevel is limiting

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#151]
Currenty, we have a few PriorityLevel values:

```go
const(
	// HighestGround is the highest PriorityLevel that will be rendered
	HighestGround PriorityLevel = 50
	// HUDGround is a PriorityLevel from which everything isn't being affected by the Camera
	HUDGround    PriorityLevel = 40
	Foreground   PriorityLevel = 30
	MiddleGround PriorityLevel = 20
	ScenicGround PriorityLevel = 10
	// Background is the lowest PriorityLevel that will be rendered
	Background PriorityLevel = 0
	// Hidden indicates that it should not be rendered by the RenderSystem
	Hidden PriorityLevel = -1
)
```

As a reminder: the usage of these is as follows: the higher the `PriorityLevel`, the later it will be rendered (so it'll be on on top). This is done by having 51 lists of `Entity`-references, and looping over each of them (see https://github.com/paked/engi/blob/master/render.go#L255-L288 ). One for each value between `Background` and `HighestGround`. 

However, it would be nice to have limitless values in between (like an ordering, instead of a grouping). 

Why not multiply those values by a million? Well, in the current workflow, this would create millions of `Entity`-reference lists, and we would have to loop over each and every one of them - including those that are empty. Using a map instead isn't desirable either, because looping over a `map` also is quite resource demanding (when doing it 50 million times within `6.944ms` (on 144hz)). 

----------------------

Possible fix: using `sort.Sort`, to actually sort based on the `PriorityLevel`. The values given at the top of this issue, can be scaled from anything between `0` and `2^32-` or so (`uint32`). When does this sorting have to take place? Well, all `Entity`s that are already part of the `RenderSystem`, are ordered. Whenever you add a new item to the `RenderSystem`, that last item would be unsorted. This gives us two possibilities:
- Sorted insertion (i.e.: we lookup where we should add it, and add it there (instead of at the end);
- Or: call sort.Sort in the `(r *RenderSystem) Post()` function, so it'll automatically sort in every added `Entity`. 

I could implement either one of those things, but before I do so, it'd be nice to hear your thoughts @paked @faide ?

**Comment by faide** [comment]
Why not change this and add a z position (layer) in the space component? And use the layer from space component ?
Look at this implementation: https://github.com/los-cocos/cocos/blob/master/cocos/cocosnode.py#L651

**Comment by EtienneBruines** [comment]
I like the idea of having a z-position (because everyone knows what it is). Wouldn't we have to do the same kind of sorting/grouping operation when we call it a z-position? The main difference between the `PriorityLevel` and a z-position, is that the `PriorityLevel` is bound to a certain `Shader` (for optimization); i.e.: everything on `PriorityLevel` 15 has the same `Shader`. Switching `Shader`s is doable, but requires a few (expensive) calls to the GPU. 

We could get rid of the `PriorityLevel` entirely, add a z-position to the `SpaceComponent`, and require every `RenderComponent` to reference to a `Shader`? (atm, you only need to worry about selecting the right `PriorityLevel`, and once you've defined your `Shader`, `engi` will do the rest; but then you'd have to reference the `Shader` each time -- which is OK). 

This would be quite a drastic (but probably worthwhile) change. @paked ?

**Comment by faide** [comment]
I like the idea of giving control of the shader to the game developer explicitly. At the cost of some added complexity.
I was wondering were the the game developer could plug its shaders.

 Maybe this would be the answer :)

**Comment by EtienneBruines** [comment]
Well, you can already plug in your Shaders at the moment, but I guess this is a nicer way of doing it.

**Comment by paked** [comment]
I'd like to not increase the amount of complexity in the engine. If we could find some way to have a fake `z` axis, and then a default shader that would be best.

**Comment by EtienneBruines** [comment]
To summarize some ideas: 
* `PriorityLevel` is to be removed
* `SpaceComponent` gets an additional Z-index (not a z-axis) - or should this be within `RenderComponent`? 
* `Shader`s can now be plugged in per-`Entity`, by calling `SetShader` on the `RenderComponent` of that `Entity`. 

We'd be having a lot of `SetShader` / `SetXXX` functions on the `RenderComponent`. I think we'd create an issue after this one, to clean that up?

**Comment by paked** [comment]
- Removing `PriorityLevel` works for me
- I'd prefer it to be on the `RenderComponent`.
- As long as we have a set of default shaders that can be used out of the box, I am fine with this.

**Comment by EtienneBruines** [comment]
I've managed to implement this quite nicely:

* Entities are now in a single list (instead of mapped per `PriorityLevel`), and sorted on `zIndex` and `Shader`. This preserves the ordering of the z-index, but also allows for optimizations in the sense that as few shader-switches occur as possible. 

PR coming up soon.
