### ISSUE TITLE
GC

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#154]
As everyone knows, Garbage Collection is a bitch. 

As most implementations will want to do some kind of VSync / Framerate limitation, it would make sense to do some GC while waiting anyway. In other words: when you're done computing what you want to do that frame, it'll usually wait a while before starting another frame. During this time, we can explicitly call the [GC](https://golang.org/pkg/runtime/#GC). 

Haven't tested this in practice (yet), but I would expect that the GC-pauses would be minimized during the frame, as the GC can do more at the time we're already waiting. 

Not sure if we need this, but at least the issue is out there.

**Comment by faide** [comment]
Agreed, but 1.5 and even more 1.6 have drastically improved the GC pauses issue in Go and I propose we wait until we reach a real case scenario in which GC pauses become an issue before try to fiddle ourselves with GC calls.

**Comment by otraore** [comment]
Up for (re-)review

**Comment by mewmew** [comment]
I second @faide's remark and think we should wait with this until there is a real case scenario in which the GC has been proven to be the culprit of the performance loss.

**Comment by paked** [comment]
I highly doubt this well **ever** be an issue given the recent GC optimisations. We could probably optimise our use of CGO before needing to come anywhere near the GC.

**Comment by mewmew** [comment]
> I highly doubt this well ever be an issue given the recent GC optimisations. We could probably optimise our use of CGO before needing to come anywhere near the GC.

Agreed. Lets close this issue for now to reflect this. If GC ever becomes an issue in the future, the issue will be archived and may be re-opened at that time.

**Comment by otraore** [comment]
Agreed @mewmew closing now.

**Comment by otraore** [comment]
Also wanted to add the fact the documentation itself says:

> GC runs a garbage collection and blocks the caller until the garbage collection is complete. It may also block the entire program.
> 

Emphasis on "It may also block the entire program"

**Comment by paked** [comment]
@otraore But realistically this is only the tiniest amount of time. If you use sane memory management practices this should never happen.

**Comment by EtienneBruines** [comment]
> Agreed @mewmew closing now.

SGTM.

**Comment by otraore** [comment]
What does sgtm mean?

**Comment by mewmew** [comment]
sounds good to me

**Comment by otraore** [comment]
Thank you @mewmew 

I was confusing it with LGTM (Lets get this merged) so I was stuck on what would the S mean.

**Comment by mewmew** [comment]
> Thank you @mewmew
> I was confusing it with LGTM (Lets get this merged) so I was stuck on what would the S mean.

Hehe, no worries. I usually interpret LGTM as looks good to me.

**Comment by paked** [comment]
@mewmew Same!

**Comment by otraore** [comment]
So maybe I had it all wrong, Oh well in the context we saw it, they kind of meant the same thing.
