### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by paked** [EngoEngine/engo#156]
The current name for this project "engi", is left over from when I forked `ajhager/engi`, way back. I think it would be better for both projects if we renamed. This would create less confusion and allow us to be seen as our own entity, as opposed to "just a fork".

It also doesn't make much sense to keep the branding because our API is *entirely* different. I actually think it would be an interesting experiment to see if there is any code we haven't touched.

Thoughts? @faide @EtienneBruines.

---

I propose we rename, and at the same time move to a GitHub organisation by the same name.

A few of my current ideas on names:

- Monocle
- Combustion
- Benzgine

Thinking out loud here, but it might be nice to have some hidden reference to the early engines of the industrial revolution... But maybe that is too deep of a reference :laughing:

**Comment by faide** [comment]
I am in favor of a name change. I wanted to propose this to you at a later point. Glad you brought the subject yourself.

I think it would also be beneficial to the project to have its own github account instead of being under your user name. Even though I could understand if you would like to keep it that way.

**Comment by EtienneBruines** [comment]
@faide I believe an "organization" (https://github.com/organizations/new) is the way to go here (instead of another GitHub account. It allows you to add team members etc., and probably some role management (not sure about that last one). 

I'm all for the name change. I'm not very creative myself, but I think any name is fine as long as it isn't too long (people will be typing it a lot).

**Comment by paked** [comment]
On the Gophers Slack, I jokingly came up with the name Dodo for our engine, as it has almost been extinct before :')

I'm not quite sure I want to keep it, but hey... It's a start!

**Comment by EtienneBruines** [comment]
Since dodo is taken, I thought why not godo. Well, that already existed, so that didn't work out. 

According to [wikipedia](https://en.wikipedia.org/wiki/Dodo#Etymology), `dodar` is an English word for `dodo` which was used until the 18th century. So that's also a possibility.

**Comment by paked** [comment]
Why is coming up with names so difficult.

Any objections if we just use dodar?

**Comment by otraore** [comment]
@paled yes

**Comment by otraore** [comment]
My suggestions:

leap
ego
engo
nyx
game (the org would need a name but the package would just be game like jordanwright/email)

**Comment by paked** [comment]
I like the idea of `engo` or `nyx`.

**Comment by otraore** [comment]
Anyone mind if we did engo? I think nyx sounds more like a game than an actual game engine.

**Comment by faide** [comment]
I like engo
Le 31 mars 2016 3:22 AM, "Ousmane Traore" <notifications@github.com> a
écrit :

**Comment by paked** [comment]
OK. So lets go with `engo`.

Unfortunately it seems that name is already taken on GitHub. I guess we could append "engine" or "games" to it?

Something like:

- `github.com/EngoEngine/engo`
- `github.com/EngoGames/engo`

OR we could add another consonant to the mix... `Engyo` Anyone (and is available on GitHub)?

**Comment by EtienneBruines** [comment]
I like the idea of `engo` (mixture between `engine` and `go`, and it even has `go` in it :smile: ). 

The name `EngoGames` gives the idea that we're producing "games", so I'd prefer `EngoEngine` over that.

**Comment by paked** [comment]
**IT IS DONE**

I've renamed the repository from `engi` to `engo`, and moved it to a brand new `EngoEngine` GitHub organisation.

**Comment by paked** [comment]
I'm assigning myself so I can make a PR to finish this off.

**Comment by EtienneBruines** [comment]
@paked could you remove the `A fork of ajhager/engi` from the description of this repo? (I cannot change it myself; no permission)

**Comment by paked** [comment]
Will do

**Comment by paked** [comment]
Aaannnd done!
