### ISSUE TITLE
Tiled example?

### ISSUE THREAD

**Issue by otraore** [EngoEngine/engo#161]
It'd be nice to have some form of example for loading in and drawing tile-maps. From what I've seen it looks like the functionality is there but the functions and some structs aren't exported. I'd like to contribute a platformer example using tiled and this would greatly help me. Thanks in advance.

**Comment by paked** [comment]
@otraore There *used* to be a tilemap example. Unfortunately it appears to be broken, I'll try and fix it up for you.

**Comment by otraore** [comment]
@paked That'd be great, Thank you!

**Comment by paked** [comment]
Status update: It looks like our tilemap implementation is completely broken. We're going to need to rewrite it.

I've created #162

**Comment by otraore** [comment]
Closing this in favor of: https://github.com/EngoEngine/engo/issues/162
