### ISSUE TITLE
Fix Tilemaps

### ISSUE THREAD

**Issue by paked** [EngoEngine/engo#162]
We used to have reasonably good support for Tilemaps. I'd like to bring our current implementation back up to this point.

**Comment by otraore** [comment]
If you need help with this, I'm willing to help out @paked.

**Comment by paked** [comment]
I have a few ideas on how we could implement this. For me, it is important we split the tilemap system into two "sections"

- Tilemap
- Loader

The Tilemap would be the actual renderable component of this, containing the information on how to render the specific tilemaps.

The Loader would be an interface which would create Tilemaps, as implied by the name it would load different types of Tilemaps (Like TMX maps, from tiled). I envision this being something like a `Decoder` from `encoding/json`, except returning a `Tilemap` instead of a having a pointer as a parameter.

**Comment by paked** [comment]
@otraore Would you be interested in taking lead on the implementation?

**Comment by otraore** [comment]
@paked Sure, I'll give it a try.

**Comment by mewmew** [comment]
Is anyone currently working on tilemaps support, or is it up for grabs? I seem to remember @Newbrict working on it?

**Comment by EtienneBruines** [comment]
@Newbrict did some work on it, IIRC.

**Comment by Newbrict** [comment]
I have it working, and it's in a PR
I've just been super duper busy with TC and what not... I'm sorry I will get the pull request fixed up friday at the latest!

**Comment by paked** [comment]
Thanks @newbrict ❤️
