### ISSUE TITLE
SVG / OpenVG support

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#167]
Right now, we have textures in the form of images (JPG/PNG/GIF?), and these can be in various resolutions based on the target-system (you could have different images for a 4K-display, than for a 240p display). While you can have different images for those different sizes (i.e. _240p.jpg, _360p.jpg, _1080p.jpg, etc.), or you can just load the highest available (always load the 4K-file, and downscale it when needed), 2D often allows you to work simply with SVG files. 

These can be scales into any resolution you want. 

Let's support those. 

According to [this stackoverflow post](http://stackoverflow.com/a/2079780), [OpenVG](https://www.khronos.org/openvg/) might also be a viable solution for this - although I'm not sure if these bindings already exist for Go. 

Up for grabs.

**Comment by mewmew** [comment]
> According to this stackoverflow post, OpenVG might also be a viable solution for this - although I'm not sure if these bindings already exist for Go.

Anthony Starks, who made svgo also made a wrapper for openvg.

https://godoc.org/github.com/ajstarks/openvg

He gave a talk at dotGo 2015, covering both of these packages https://www.youtube.com/watch?v=nuDO1oQxARs

**Comment by paked** [comment]
@mewmew If we were to do use this library we would have to make another wrapper, along the same lines as engoengine/audio or engoengine/gl. It uses CGO, but I imagine SVG support on webgl is easier than native.

**Comment by mewmew** [comment]
It would also be interesting to look into https://github.com/llgcode/draw2d

**Comment by Noofbiz** [comment]
I've actually been wondering if there is any libraries in go for this already? Parsing an svg shouldn't be hard with encoding/xml and then drawing the image with that draw2d

**Comment by jonbonazza** [comment]
I'd prefer to keep this pure go. We should strive to limit CGO usage as much as possible.

**Comment by Noofbiz** [comment]
There's a few go svg parsers but nothing is very robust, mostly just fit for their use cases. The best one I've seen is attached to [gi](https://github.com/goki/gi) and one for pdfs. It's a fork of [this](https://github.com/rustyoz/svg) with additional features added.

**Comment by hajimehoshi** [comment]
Interesting: does that library do software rendering?

**Comment by Noofbiz** [comment]
Yeah, right now it just decodes to an image.Image and then uses it just like a png etc. When I add beizer curves, arcs, and rounded rectangles to the shapes I should be able to implement the rasterizer directly on opengl, as the rasterizer for the library is an interface. I used  srwiley/oksvg
