### ISSUE TITLE
Fancy Logo

### ISSUE THREAD

**Issue by paked** [EngoEngine/engo#169]
I think we should get a logo for the new organisation. Any ideas?

**Comment by paked** [comment]
From @otraore [on the gitter](https://gitter.im/EngoEngine/engo):
```
- https://github.com/golang-samples/gopher-vector
- I'm thinking add a game controller to the gophers hands?
- Also you can add the domain to the github organization
```

**Comment by paked** [comment]
Update on this. We had an artist do a water marked draft version: ![http://i.imgur.com/QLPN4He.png](http://i.imgur.com/QLPN4He.png)

**Comment by EtienneBruines** [comment]
TODO: what would this look like 64x64 pixels? And 128x128? (something smal)

**Comment by EtienneBruines** [comment]
The file is a bit huge, but we could also go for something a bit more ... simplistic. 

![gopher-controller](https://cloud.githubusercontent.com/assets/3962174/14400924/2ffd70e4-fe01-11e5-9f15-0b3d45d6c338.png)


Note that I'm not saying one is better than the other - just saying there's a choice.

**Comment by paked** [comment]
Why don't we compare what they look at scaled sizes?

I have a feeling your one will work better.

**Comment by EtienneBruines** [comment]
@paked https://www.huperwebs.nl/comparison.html

**Comment by otraore** [comment]
In terms of looks I think the [one made by the designer](https://camo.githubusercontent.com/81386d2e3cf6ba8812c90e9c959fc37737a6f506/687474703a2f2f692e696d6775722e636f6d2f514c504e3448652e706e67) looks better. The other one looks a bit weird 😜  . It looks as if you're giving the gopher something inappropriate (maybe just me).

**Comment by EtienneBruines** [comment]
Not yet seeing the weird part :P But it looks more like a controller on his shirt, than the controller he's holding in his hand on the one made by the designer.

**Comment by otraore** [comment]
@EtienneBruines well if you give him a shirt that could work.

**Comment by EtienneBruines** [comment]
A tattoo, in that case? Didn't notice he wasn't wearing anything.

**Comment by paked** [comment]
@EtienneBruines @otraore I think we should go with the designers one, but we should see if we can fit any colours onto the control. That might make it even easier to see at a small resolution.

**Comment by otraore** [comment]
@paked Sure make sure to tell the designer and I'm sure he'll make the adjustments.

**Comment by yra99ary** [comment]
![w](https://cloud.githubusercontent.com/assets/8791195/14536750/94293680-02a6-11e6-8f25-8202477a65a0.png)
Hi guys,do you like this flat style?

**Comment by HeadClot** [comment]
@yra99ary - I like the flat style but there seems to be visible seems in the center of the gopher.

**Comment by paked** [comment]
Everyone, thanks for your support with this (Especially those of you who mocked up their own designs!). We've decided to go forwards with this design:

![](http://i.imgur.com/hb25tl6.png)

If you have any violent objections, please create a new issue.

**Comment by otraore** [comment]
🎉
