### ISSUE TITLE
AudioSystem on Windows

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#174]
Currently, the `AudioSystem` is only available on Linux/Android/OSX. 
This should be addressed.

**Comment by paked** [comment]
We should also look at OSX deps

**Comment by EtienneBruines** [comment]
We should; but that's more something for #175. Audio was working fine (at least that's what I've heard; I don't have any Apple devices).

**Comment by otraore** [comment]
Audio is working fine on OSX, updating issue.

**Comment by mewmew** [comment]
It may be worth comparing the current implementation to https://github.com/hajimehoshi/ebiten/blob/master/audio/internal/driver/driver_windows.go which also implements a Windows backend for playing audio.

**Comment by EtienneBruines** [comment]
@mewmew Nice source. I'd like to note that OpenAL is not used in that example. Why would you want OpenAL? So you can define a location / direction for the audio. Moving the Camera around, almost automatically handles the volume of all audio sources.

**Comment by otraore** [comment]
Closed in favor of: https://github.com/EngoEngine/engo/issues/272
