### ISSUE TITLE
LICENSE / NOTICE file

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#178]
After doing some reading, we've come up with the following information:

We should include a `NOTICE.md` file in our repository, which lists all `LICENSE`s `engo` depends on. This includes Go itself (BSD license), probably `ajhager/engi`, and possibly all other packages we depend on. 

Those that use `engo` to compile something, should include that NOTICE file with that binary (those annoying README files you see with games you install). 

See also http://opensource.stackexchange.com/questions/1711/combining-code-written-under-different-licenses-eiffel-forum-license-mit-and-a

**Comment by otraore** [comment]
I recommend you just add a "Credits" or "Copyright" section to you game (Those long sections that people barely read).

**Comment by otraore** [comment]
https://github.com/EngoEngine/engo/issues/188https://github.com/EngoEngine/engo/issues/188 will also benefit from this

**Comment by mewmew** [comment]
> We should include a NOTICE.md file in our repository, which lists all LICENSEs engo depends on.

Is it conventional to use a `NOTICE` file to track licenses of third-party projects? Which other projects use this approach?

Along @otraore's reasoning, I'd suggest simply adding a bullet list in the [credits section of the readme](https://github.com/EngoEngine/engo#credits) and simply stating their license, or better yet providing a link to their original license file. E.g.

* The Lux engine, which provides a `float32` [math](https://godoc.org/github.com/luxengine/math) package ([MIT license](https://github.com/luxengine/math/blob/master/LICENSE))

**Comment by otraore** [comment]
I think what @mewmew says is a good idea, unless anyone wants to argue against it, I'm going to send a PR soon to implement it

**Comment by paked** [comment]
@otraore This works for me!

**Comment by otraore** [comment]
@paked Great!

**Comment by otraore** [comment]
Closed by https://github.com/EngoEngine/engo/pull/248
