### ISSUE TITLE
View Culling

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#180]
It'd be nice if OpenGL only drew what was seen by the Camera.

**Comment by HeadClot** [comment]
This would be great a great performance saving feature for #196

**Comment by otraore** [comment]
I want to make another suggestion and give the option to only draw things x distance from the camera  and not things right at the edge to lower chances of seeing blank area while rendering. This would have a default and be modifiable by the user.

**Comment by paked** [comment]
@otraore Sounds good to me!

**Comment by EtienneBruines** [comment]
> and not things right at the edge

Could you elaborate on this?

**Comment by boombuler** [comment]
Implemented in https://github.com/EngoEngine/engo/pull/636
