### ISSUE TITLE
Error upon trying to import engo

### ISSUE THREAD

**Issue by ryanisaacg** [EngoEngine/engo#182]
I am running Linux Mint 17.2, if it helps. 

I installed the dependencies with the command `sudo apt-get install libopenal-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev xorg-dev libgl1-mesa-dev`

Then I used the command `go get -u github.com/engoengine/engo` to get the library.

I made a new file `~/test.go` to try the Getting Started example, and I pasted the contents into the file.

When I ran `go run test.go` I got the following error message:

    test.go:4:5: cannot find package "github.com/EngoEngine/ecs" in any of:
	    /home/ryan/bin/go/src/github.com/EngoEngine/ecs (from $GOROOT)
	    /home/ryan/go_workspace/src/github.com/EngoEngine/ecs (from $GOPATH)
    test.go:5:9: cannot find package "github.com/EngoEngine/engo" in any of:
	    /home/ryan/bin/go/src/github.com/EngoEngine/engo (from $GOROOT)
	    /home/ryan/go_workspace/src/github.com/EngoEngine/engo (from $GOPATH)

I checked, and the path `/home/ryan/go_workspace/src/github.com/engoengine/engo` exists. Is there a case sensitivity issue or is there another problem? If it's case sensitive how would I fix it?

Thanks!

**Comment by paked** [comment]
@ryanisaacg Sorry, what contents did you put into the `test.go` file?

The easiest way to fix this is to run `go get -u github.com/EngoEngine/ecs`.

**Comment by paked** [comment]
Let me know if this works, and I'll close the issue!

**Comment by ryanisaacg** [comment]
I now get the error `package main: case-insensitive import collision: "github.com/EngoEngine/ecs" and "github.com/engoengine/ecs"`

The file contents is the example at https://github.com/engoengine/engo/tree/master/demos

**Comment by paked** [comment]
@ryanisaacg Have you deleted `github.com/EngoEngine/ecs` from your path?

**Comment by ryanisaacg** [comment]
No, I have not.

**Comment by paked** [comment]
I'd do that, then everything should be fine.

**Comment by ryanisaacg** [comment]
By path, do you mean `$PATH`?

**Comment by paked** [comment]
Sorry, I meant removing it from your `$GOPATH`. So if `$GOPATH/src/github.com/EngoEngine/ecs` exists, you should delete it.

**Comment by EtienneBruines** [comment]
The quick-and-dirty fix at the moment is to make sure `$GOPATH/src/github.com/engoengine/` exists, and then create the subfolders `ecs`, `engo` and `webgl` by using `git clone` for each of them. 

We're working towards fixing the problem in general, but that might take us a few days to figure out. Thank you for your patience. If you need any help getting the quick-and-dirty fix to work, don't hesitate to ask us at [Gitter](https://gitter.im/EngoEngine/engo) - we'll try to help you out :-).

**Comment by ryanisaacg** [comment]
I tried at @EtienneBruines 's suggestion but now I'm getting a new error (output below).

     # command-line-arguments
    ./test.go:12: undefined: engo.SetBg
    ./test.go:12: undefined: color in color.White
    ./test.go:34: cannot use Game literal (type *Game) as type engo.Scene in argument to engo.Run:
        	*Game does not implement engo.Scene (missing Hide method)

**Comment by paked** [comment]
@ryanisaacg My apologies. It looks like that example is out of date. Would you mind using the code in https://github.com/EngoEngine/engo/blob/master/demos/entity/entity.go, instead?

**Comment by EtienneBruines** [comment]
* `engo.SetBg` has been renamed to `engo.SetBackground`
* `color` has to be imported from `image/color` (standard Go library)
* Guess your `Game` doesn't implement the `engo.Scene` interface as defined here:

```go
// Scene represents a screen ingame.
// i.e.: main menu, settings, but also the game itself
type Scene interface {
	// Preload is called before loading resources
	Preload()

	// Setup is called before the main loop
	Setup(*ecs.World)

	// Show is called whenever the other Scene becomes inactive, and this one becomes the active one
	Show()

	// Hide is called when an other Scene becomes active
	Hide()

	// Type returns a unique string representation of the Scene, used to identify it
	Type() string
}
```

**Comment by paked** [comment]
@EtienneBruines He is using the getting started example, which has gone out of date. We need to update it.

**Comment by EtienneBruines** [comment]
@paked I was wondering where he got the code. My apologies @ryanisaacg - I'll fix this right now at the wiki.

**Comment by EtienneBruines** [comment]
The updated version might work a bit better.

**Comment by ryanisaacg** [comment]
The new code works much better, thanks everybody!

**Comment by paked** [comment]
@ryanisaacg Thanks for using `engo`. If you are having any problems, please don't hesitate to reach out on [gitter](https://gitter.im/EngoEngine/engo) or [file an issue](https://github.com/EngoEngine/issues/new).

![https://media.giphy.com/media/dc7LsyKabZ6Ra/giphy.gif](https://media.giphy.com/media/dc7LsyKabZ6Ra/giphy.gif)
