### ISSUE TITLE
Give credit to hydroflame/luxengine

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#188]
We're using the `math` library for `float32` at https://github.com/luxengine/math. 

Even though the MIT license doesn't force us to do anything, I think it'd be nice / fair to mention libraries like this in our "Credits" section. 

Are you OK with this, @paked?

**Comment by Newbrict** [comment]
Where do we use that?

**Comment by paked** [comment]
@Newbrict We use it in [`assets.go`](https://github.com/EngoEngine/engo/blob/bbec375377fca7fe542262c97633fde225d60333/assets.go).

**Comment by mewmew** [comment]
The general issue discussing how give credit to third-party projects is in #178.

**Comment by otraore** [comment]
Fixes by https://github.com/EngoEngine/engo/pull/248
