### ISSUE TITLE
CameraSystem - non-instant movements

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#191]
Do we want to animate camera movement? Now we can say "MoveTo", and it instantly moves the camera to that position. Would it be neat to be able to say `MoveToIn(some_location, some_duration)`? i.e. to be able to add a duration? 

Or would we just let the user implement this by updating the camera location each frame?

**Comment by paked** [comment]
Yes. From memory, the original camera had this build in. Pretty easy lerp
based stuff.

**Comment by EtienneBruines** [comment]
I think I can do this tomorrow (Sunday 17th).

**Comment by paked** [comment]
@EtienneBruines Would you like me to take this off your hands?

**Comment by EtienneBruines** [comment]
Not sure why there's no reference (must've forgotten it). 

Fixed as of https://github.com/EngoEngine/engo/commit/719360415b8b5359e610be03c416b980d6c60965. See also https://github.com/EngoEngine/engo/pull/209.
