### ISSUE TITLE
Messaging System is clunky

### ISSUE THREAD

**Issue by paked** [EngoEngine/engo#2]
Currently when subscribing to an event you pass in the system and the event name. This is clunky and leads to too much message confirmation logic in the default `System.Receive(msg Message)` handler.

My proposal is to pass a `type func(msg Message)` when subscribing to an event instead.

Any objections?

**Comment by mewmew** [comment]
For future reference, the proposal was implemented with commit 8d2cc584208e6780a441a4d4a41051725cd64eff as far as I can tell.
