### ISSUE TITLE
Tutorials at Github

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#201]
Do we want the tutorials (including issues for them, like #30 and #31) to stay? 

Or do we want to expand our tutorials at https://engo.io and remove those others from Github (wiki) to avoid confusion?

Thoughts @paked ?

**Comment by paked** [comment]
@EtienneBruines Lets move all of our tutorials onto the website.

**Comment by otraore** [comment]
@paked I agree. Maybe link the site in the wiki?

**Comment by paked** [comment]
Yep.
