### ISSUE TITLE
Texture cleanup

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#211]
As noted in the comments at #135, we currently have no way to dispose of a `Texture`. A texture is being created on the GPU-side, but if we stop using our `RenderComponent` / `Texture`, that doesn't remove it from the GPU-side (causing memory leak). 

As Go doesn't have destructors, I believe we should just create some kind of cleanup function. Possible names:
* `Delete`
* `Remove`
* `Close` (yes, it's weird, but most people know they should `Close` whenever they can)

Thoughts everyone?

**Comment by paked** [comment]
Lets use Close.
