### ISSUE TITLE
Naming of Width/Height WindowWidth/WindowHeight

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#212]
The naming is currently horrible. 

We have two variants, both with width/height:
`WindowWidth` and `Width`. 

Currently, `WindowWidth` is a 1:1 match with the width in pixels of your game window. The `Width()` (which is the private variable `gameWidth`), is a bit more unclear. It's a 1:1 match with the width of your game window, **iff** `ScaleOnResize` is set to false. In other words, the `gameWidth` does not change if the window size changes. 

We should come up with better names, and document it better.

**Comment by paked** [comment]
I think GameWidth and WIndowWidth would be good. Where game is the amount
of pixels which Camera perceives, and WindowWidth is the amount of pixels
the OS would see.
