### ISSUE TITLE
WebGL is named "Web"GL

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#218]
As @otraore mentioned, our `engo.io/webgl` package, is called **web**gl. Even though it's not web-only. 

Let's come up with a better name, because this package serves as a compatibility-layer between us and OpenGL/WebGL versions (web, desktop, possibly mobile).

**Comment by paked** [comment]
`optimusGL` ;)

**Comment by paked** [comment]
@otraore Can we close this yet? Since `webgl` is now `gl`?

**Comment by EtienneBruines** [comment]
Yes.
