### ISSUE TITLE
Joystick/Controller Support

### ISSUE THREAD

**Issue by paked** [EngoEngine/engo#221]
As a game engine I think it would be really cool for us to experiment with some other input mechanisms. One of the libraries I found which could do this for us is: https://github.com/simulatedsimian/joystick.

In terms of implementation, I imagine that we would add a "JoystickSystem" to the game, which would then fire messages when respective buttons were pressed.

**Comment by otraore** [comment]
https://github.com/luxengine/ctrl looks pretty cool

**Comment by otraore** [comment]
I have an xbox one controller now and I might give this a shot in the near future.

**Comment by yarbelk** [comment]
I *really* like the steam controller design (not nessicarially the implementation).  A bit different from 'just suport joystick', but rather thinking a bit more about 'control pane' + whatever you wanted to back it up; so you can have keyboard, gamepad and joystick all in use at the same time.

**Comment by jonbonazza** [comment]
I have a PS4 controller that I could test this with, and I also have a wireless XBox360 controller, but I don't have the necessary dongle for PC usage. That said, I need to pick one up for another project anyway, so I should be able to test both of these controllers if needed.

**Comment by Noofbiz** [comment]
Added control support for glfw and browsers. We can add more support as needed. Tested with PS4 and XBox controllers.
