### ISSUE TITLE
Exit optional

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#224]
I've just been working on reworking `ecs`, and noticed that it's relatively easy to use interfaces to make certain functions optional. 

```go
type Exiter interface {
    Exit()
}

func whateverWeDoOnExit() {
    if exiter, ok := currentScene.(Exiter); ok {
        exiter()
    }
    // ...
}
```

This way, if they don't implement `Exit()`, it's OK (because no code is run). If they were to implement it, we would run it. 

As you made the current implementation, what's your thought on this, @otraore ?

### Show and Hide

Same goes for `Show()` and `Hide()` I guess, interfaces `Shower` and `Hider` would work.

**Comment by paked** [comment]
I'm not quite sure how idiomatic this is. Would you mind providing a more complete coding example?

**Comment by EtienneBruines** [comment]
Well, there's only one place:
## where we call `scene.Hide()`
namely [here](https://github.com/EngoEngine/engo/blob/master/scene.go#L56);
I want to replace this one line, with these 3 lines:
```go
if hider, ok := currentScene.(Hider); ok {
    hider.Hide()
}
```

## where we call `scene.Show()` 
(there should be, but there isn't one);
This one line, that isn't there but should be, I would replace with these 3 lines:

```go
if shower, ok := currentScene.(Shower); ok {
    shower.Show()
}
```


## where we call `scene.Exit()`
namely [here](https://github.com/EngoEngine/engo/blob/master/engo_glfw.go#L210). 
I want to replace this one line, with these 3 lines:

```go
if exiter, ok := scenes.scene.(Exiter); ok {
    exiter.Exit()
}
```

---------

An example in the Go environment that uses this, is the `http.Flusher` interface. Not all `http.ResponseWriter`s implement it, and therefore if you want to usage, the [recommended usage](http://stackoverflow.com/a/19292461/3243814) is:

```go
if flusher, ok := w.(http.Flusher); ok {
    flusher.Flush()
}
```

**Comment by otraore** [comment]
I'm all for it, I did think at first it was weird having to leave empty functions you didn't use because you have to meet the interface. I'm all for it @EtienneBruines since it also seems to be idiomatic go being used in the standard lib.

**Comment by paked** [comment]
If it is used in the stdlib, I'm OK with it. Lets just be careful not to overdo it.

**Comment by EtienneBruines** [comment]
Will do after #225.
