### ISSUE TITLE
Revisit WorldBounds

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#228]
Currently, we have `WorldBounds`, a global variable which allows you to set an `AABB` of where the game-world should be. These are being considered "holy" by the `CameraSystem` - you cannot move outside these bounds. 

The `WorldBounds` currently defaults to the window dimensions as defined in the `RunOpts`. 

Do we want to keep this behavior? It looks a bit weird in the demos, so maybe we should include setting the `WorldBounds` in the demo?

**Comment by Newbrict** [comment]
you can set the with WorldBounds.Max = ___
what's wrong with this behavior?

**Comment by EtienneBruines** [comment]
The fact that it's never being done in any of the examples. 

Or maybe its default value? 

The thing you can set isn't that bad at all, though.

**Comment by Newbrict** [comment]
So this issue only pertains to the demos?

**Comment by EtienneBruines** [comment]
At least to the demos; whether or not we want default values at all, and what those values should be, might be a decision we could make.

**Comment by paked** [comment]
In my past experiences with other 2D engines the default values for the WorldBounds (or equivalent) are that of the window dimensions.

I think it is fine to leave this as is for now.

**Comment by EtienneBruines** [comment]
Should we updated some demos (such as the `hud` demo) to use custom-defined values? Or design the demos in such a way that the "background" drawn also matches `WorldBounds`?

**Comment by paked** [comment]
@EtienneBruines As long as the `WorldBounds` properly reflects the space used in the demo, I am happy.
