### ISSUE TITLE
Multitexturing

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#231]
Basically, "blending" multiple textures over another. Like a path over a grass background. 

Short video describing how to do it in Java: https://www.youtube.com/watch?v=-kbal7aGUpk&list=PLRIWtICgwaX0u7Rf9zkZhLoLuZVfUksDP&index=17

**Comment by paked** [comment]
I initially was a bit confused as to what we would gain from this over traditional tilemaps, but after watching the video I realised that this could be pretty damn cool in a 2D game.

**Comment by EtienneBruines** [comment]
This requires a user-generated blend-map (indicating the proportions of how much to render each texture), and of course, multiple textures "combined". 

Roughly: 
* We need a way to allow rendering of "a group of textures", maybe create a `type MultiTexture` which allows this. 
* Within our Shader, we would then call `Gl.ActiveTexture(Gl.TEXTURE0)` for each of those textures (with the `0` incrementing)
* Our FragmentShader needs to be passed the BlendMap values, so it can figure out how much of which to render. 
* Our FragmentShader needs a list / binding of which texture to use for certain R/G/B values.
