### ISSUE TITLE
Font atlas

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#232]
A lot of our font rendering is being done on the CPU-side (read: all of it). 

Instead, we should render each character (pretty much the ASCII alphabet) into a single "texture", and use an "atlas" (sort of like a spritesheet), to indicate which character OpenGL should draw. 

A video on how to do this in Java: https://www.youtube.com/watch?v=mnIQEQoHHCU&list=PLRIWtICgwaX0u7Rf9zkZhLoLuZVfUksDP&index=32

**Comment by paked** [comment]
@Newbrict You wrote the original version of the current font renderer, what do you think of this?

**Comment by Newbrict** [comment]
In the past we used an atlas. but we used a monospace atlas. If you want to build this out either we need a very detailed explanation on how to create the proper font files to be used, or the atlas creation has to be done on preload from ttf file.
unless a lot of code goes into this, using an atlas is way less usable than just rendering on the cpu

**Comment by Newbrict** [comment]
Also from what I remember you can really optimize my font renderer. I don't cache anything where you could

**Comment by Newbrict** [comment]
Cache the texture?

**Comment by EtienneBruines** [comment]
Not that much can be cached. There's some progress in #330, although I didn't test the performance yet.
