### ISSUE TITLE
Allow for MSAA

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#233]
Multi-sampling AA allows to smoother edges. Higher values come with higher costs, but it's fairly easy to implement.

The default is at `1` (so only a single sample), but some games offer higher values (2, 4, 8, 16). 

It'd be nice if we offered to change this in our `RunOpts`. 

More info here: https://www.youtube.com/watch?v=Pdn13TRWEM0&list=PLRIWtICgwaX0u7Rf9zkZhLoLuZVfUksDP&index=41

**Comment by EtienneBruines** [comment]
Okay, tbh... Either my implementation doesn't work, or it's just not useful for the pictures I tested them with.

**Comment by paked** [comment]
@EtienneBruines I'd suspect the latter.

**Comment by Newbrict** [comment]
how does this help in 2D?

**Comment by EtienneBruines** [comment]
@Newbrict it will help with lower resolution images looking better; but I guess using a higher resolution image is probably preferred.

**Comment by EtienneBruines** [comment]
When drawing shapes, this matters. 

# Non-AA
![](https://www.huperwebs.nl/upload/screenshot-2016-05-04_14:03:12.jpg)

# With AA
![](https://www.huperwebs.nl/upload/screenshot-2016-05-04_14:07:48.jpg)

**Comment by EtienneBruines** [comment]
Fix will be part of https://github.com/EngoEngine/engo/pull/266.
