### ISSUE TITLE
engo.SetBackground

### ISSUE THREAD

**Issue by Newbrict** [EngoEngine/engo#235]
This really feels like an artifact of old engi

SetBackground should be part of the render system

**Comment by EtienneBruines** [comment]
Any suggestions on how to do so? 

Currently the `RenderSystem` is used as a one-off "add and forget" kinda thing. This change would require everyone to assign the `RenderSystem` to a variable, to be able to call the `SetBackgroud` function on it. Maybe there's a better solution than this one?

**Comment by paked** [comment]
We could do something fancy with messages?

**Comment by EtienneBruines** [comment]
I would say it's not part of the render system, but more of the "window creation", as a possible setting. 

You can set width, height, fullscreen, title, fps limit. Why not add `Background` to that list?

**Comment by otraore** [comment]
What does the ready label even mean @EtienneBruines ?

**Comment by EtienneBruines** [comment]
`ready` to be worked on. `ready` to start coding if someone wants.

**Comment by otraore** [comment]
@EtienneBruines why not `help-wanted` ?

**Comment by EtienneBruines** [comment]
Hmm. No particular reason. I always thought of `help-wanted` like "we won't be able to do this ourselves any time soon". While `ready` might be useful for us when we are bored and just wanna fix issues.

**Comment by mewmew** [comment]
I've always thought of the "help wanted" label as *this issue is up for grabs*.

Quickly using Google to find a subset of the Internet which confirms this belief, and simply remain oblivious to the first 10 or so search results which holds a different opinion : )

From https://news.ycombinator.com/item?id=9306794
> I sometimes put a `help-wanted` tag on GitHub issues I think are especially well-bounded items someone could contribute. It looks like other people use that tag, too: https://github.com/search?l=&p=2&q=state%3Aopen+label%3Ahelp...
>
> You can further filter that by language, or other criteria.

**Comment by EtienneBruines** [comment]
@mewmew I think I'll use that definition in the future. :smile:
