### ISSUE TITLE
Pong demo has too much name confusion

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#241]
We have a struct called
* `Ball`
* `BallSystem`
* `ballEntity` (beloning only to the `BallSystem`, shouldn't be used anywhere else). 

@Newbrict and I thought it'd be nice to rename it to `BounceSystem` and `bounceEntity`.

**Comment by mewmew** [comment]
Haha, misread the `bug` label as *hug*. Thought it was very sweet to give an issue a hug.
