### ISSUE TITLE
Evaluate how a minimal engo API may look like

### ISSUE THREAD

**Issue by mewmew** [EngoEngine/engo#245]
I'd like to evaluate which parts of `engo` make up the *core* of the engine. In particular, it would be interesting to find out whether we may arrive at a minimal API, from which common systems and components may be implemented as standalone packages, which would use composition, message-passing and prioritization of systems as provided by `ecs` and `engo`.

An initial evaluation has identified the six base components and six base systems, namely.

1. AnimationComponent
2. AudioComponent
3. CollisionComponent
4. MouseComponent
5. RenderComponent
6. SpaceComponent

and

1. AnimationSystem
2. AudioSystem
3. CameraSystem
4. CollisionSystem
5. MouseSystem
6. RenderSystem

I think it would be a show of strength if `engo` could be implemented as a set of decoupled packages using the principles behind ECS.

I am proposing that we evaluate the feasibility of extracting these systems and components out from `engo` and creating dedicated packages for them. It is too early to tell what effects this may have on the resulting API, and we may very well decide that a single monopackage is the way to go. Still, using this as a thought-experiment it would be interesting to see the dependencies between different parts of the `engo` engine brought into light by this evaluation.

An obvious place to start is to create a dedicated package for each component and system, but also one for the window handling, as `engo` may be used headless and a clean separation between the engine and its window handling would result in a much cleaner design.

What are your thoughts on this? Is it worth evaluating?

**Comment by mewmew** [comment]
From commit mewpull/engo@131842414d833847eb2a89b2d992da4b372a3146.

> Initial separation of engo into small packages.
> 
> This is still very preliminary work. Follow-up commits
> will TODOs related to the split, and further decouple
> packages from one another.
>
> Updates EngoEngine/engo#245.

The *core* branch at https://github.com/mewpull/engo/tree/core is tracking preliminary work at evaluating what the minimal API of `engo` may look like, and whether it is possible to decouple components from one another.

**Comment by mewmew** [comment]
A [modified version](https://github.com/mewspring/junk/tree/master/glyph) of [Dave Cheney's glyph command](https://godoc.org/github.com/davecheney/junk/glyph) was used to visualize the dependencies between the `engo` packages of the experimental *core* branch. The modified version of `glyph` excludes standard library packages from the graphs, to focus on the interesting parts, namely the intricate dependencies between different parts of `engo`.

Including some preliminary results below.

* Dependencies of the now minimal `engo` package and the recursive dependencies of its imports.

![engo recursive dependencies](https://i.imgur.com/RDXJa8G.png)

* Dependencies of the now minimal `engo` package highlighted.

![engo dependencies highlighted](https://i.imgur.com/CBh9w7F.png)

* Dependencies of the new `collision` package.

![collision dependencies](https://i.imgur.com/YLBYNoH.png)

The collision package is a perfect example of a decoupled package, which only use core parts of the `engo` API to provide a specific functionality (collision detection). Personally, I'd love it if more packages were decoupled in this manner, and only a selective few had the dependency graphs of the `engo` (and `window`) packages.

Well, this is still very preliminary work. Just wanted give a teaser which me may use as the basis for discussions.

To produce these dependency graphs, run the following.

```
[~]$ export GOPATH=/tmp/go
[~]$ mkdir -p $GOPATH/src/engo.io
[~]$ cd $GOPATH/src/engo.io
[/tmp/go/src/engo.io]$ git clone -b core https://github.com/mewpull/engo
[/tmp/go/src/engo.io]$ go get engo.io/engo/...
[/tmp/go/src/engo.io]$ go get github.com/mewspring/junk/glyph
[/tmp/go/src/engo.io]$ $GOPATH/bin/glyph 
```

Then navigate to http://127.0.0.1:8080/chord/engo.io/engo, http://127.0.0.1:8080/chord/engo.io/engo/collision, etc. `glyph` comes with several visualization modes. I've mostly been using "chord" and "tree", but the others may be interesting as well.

**Comment by EtienneBruines** [comment]
Those are some nice graphs. How did you remove the dependencies of the camera / space? 

Things like:
* `CameraSystem` depends on `SpaceComponent` (as do a lot of other systems)
* `RenderSystem` depends on `CameraSystem` (heavily)

**Comment by EtienneBruines** [comment]
This kinda looks pretty nice. 

Not sure if I like what it does to components used by multiple systems (the `SpaceComponent` and `RenderComponent` are used quite often), but that's just a matter of taste, I guess.

**Comment by mewmew** [comment]
> This kinda looks pretty nice.

I also think it is worth looking into.

> Not sure if I like what it does to components used by multiple systems (the SpaceComponent and RenderComponent are used quite often), but that's just a matter of taste, I guess.

After the evaluation finishes and we discuss the matter, there may very well be a set of *base* or *core* components which are deemed so essential that it doesn't make sense to decouple them from the general `engo` engine. However, some things like spritesheets or tmx support seems like obvious candidates, as these are not likely to be used in *every* game.

Lets keep this issue open as we continue our discussions, and see what the minimal API of `engo` may look like once we settle for an approach. My main wish is that the `System`s and `Component`s that do end up in the core `engo` engine are well motivated to be there.

**Comment by mewmew** [comment]
To summarize, the current `engo` package will be split into two packages `engo` and `core`. The `engo` package will implement the minimal engine API upon which useful `System`s and `Component`s may be built.

# Engo

* Window handling (glfw, GopherJS, mobile backends)
* Input handling (keyboard, mouse, game controllers)
* Message passing/event handling

# Core

Every `System` and `Component` implementation.

* 2D Rendering
* Audio
* Physics
* ...

For background, see the gitter discussion starting at https://gitter.im/EngoEngine/engo?at=571cb3277469496137b8aeed

**Comment by paked** [comment]
**FYI I don't want to proceed with this until we have closed #71. Rather scared of the consequences it would have for @otraore :D**

**Comment by otraore** [comment]
I agree @paked :D

**Comment by mewmew** [comment]
Just to keep notes in one place.

From https://gitter.im/EngoEngine/engo?at=571edc676e3ae55e37ea0e63

> So, (a future) `engo.io/audio` implements audio playing support for multiple platforms (desktop, js, mobile). `engo` provides a tidy API for all the basic parts of the game engine, such as window handling, input and events, message passing, audio (and something else?). Then the `core` package would implement `System`s and `Component`s using the engo API.

**Comment by EtienneBruines** [comment]
I'd love for this to "wait" until PR's https://github.com/EngoEngine/engo/pull/274, https://github.com/EngoEngine/engo/pull/273 and https://github.com/EngoEngine/engo/pull/266 are merged. Those combined change about 2k lines of code throughout the project. 

Do we also want to wait for https://github.com/EngoEngine/engo/pull/251 ? @paked @mewmew @otraore ?

**Comment by paked** [comment]
Let's do a feature freeze while we make these changes. Basically get as
much merged in as possible, and then split core and engo.

**Comment by mewmew** [comment]
> I'd love for this to "wait" until PR's #274, #273 and #266 are merged. Those combined change about 2k lines of code throughout the project. 

Definitely. The split into `engo` and `core` will be affect almost every part of the engine, so having large PRs merged first makes a lot of sense.

> Do we also want to wait for #251 ? @paked @mewmew @otraore ?

We could go either way with #251. As the current assets package is tied into basically everything of engo we may as well wait with #251 and do it at the same time as we do the split. At least, I think it may be easier to do both at the same time, but I may be convinced otherwise.

> Let's do a feature freeze while we make these changes. Basically get as much merged in as possible, and then split core and engo.

Sounds like a plan.
