### ISSUE TITLE
Input Proposal

### ISSUE THREAD

**Issue by paked** [EngoEngine/engo#252]
# Input Proposal

Our current input "system" (hint: it isn't an ECS system) has been the way it is for a solid two years now. As the the rest of the engine has evolved, input seems to have remained relatively static. This is probably a good thing, at least we implemented something right the first time! However, I'd like to propose a few changes which I think will greatly improve interacting with input with Engo.

We've recently been looking at bringing Engo to new platforms: #243 (Universal Windows Platform), #247 (Web), #63 (Mobile). With the introduction of these new platforms we are now able to investigate new forms of input like joysticks and touch. I feel the current input API is a bit too brittle to make games in this fashion.

Hypothetically, I have a game which I want to release onto my Xbox and Mac/Windows/Linux. In this game my player walks around the world (which is really god damn pretty because of all the cool work @EtienneBruines has done on the rendering). Currently, this would look like this:

```go
if engo.Keys.Get(engo.W).Down() || engo.Joystick.Get(engo.UpDirection).Down() {
    space.Position.Y -= speed * dt;
}

if engo.Keys.Get(engo.S).Down() || engo.Joystick.Get(engo.DownDirection).Down() {
    space.Position.Y += speed * dt;
}

if engo.Keys.Get(engo.A).Down() || engo.Joystick.Get(engo.LeftDirection).Down() {
    space.Position.X -= speed * dt;
}

if engo.Keys.Get(engo.D).Down() || engo.Joystick.Get(engo.RightDirection).Down() {
    space.Position.X += speed * dt;
}

if engo.Keys.Get(engo.Space).Down() || engo.Joystick.Get(engo.AButton) {
    playerComponent.CheckForItem()
}
```

I propose that we have an API which looks something like the following:

```go
vert := engo.Input.Axis("vertical")
space.Position.Y += vert.Value() * speed * dt

hori := engo.Input.Axis("horizontal")
space.Position.X += hori.Value() * speed * dt

if engo.Input.Button("action").Down() {
    playerComponent.CheckForItem()
}
```

Basically what we have here is a new input system based off of `Axis` and `Button` types.

```go
type Axis interface {
    Value() float32 // A value from -1.0 to 1.0 representing the state of an
                    // axis. For a joystick the value will change depending on how far it has been
                    // pushed in a certain direction. For a key, it will be 1 if the first
                    // element of a pair is pressed, 0 if nothing is pressed and -1 if the second
                    // value of the pair is pressed.
    Pairings() []AxisPair
}

type Button interface {
    Down() bool
    JustPressed() bool
    JustReleased() bool
    Pairings() []Key
}

```

Before you use an Axis or button you have to register it:

```go
// Register an axis with key "vertical". Uses the pairs W and S, Up and Down, and up and down on the joystick. Priority is in the same order.
engo.Input.RegisterAxis("vertical", AxisKeyPair{W, S}, AxisKeyPair{Up, Down}, AxisJoystickPair{UpDirection, DownDirection})

// Register an axis with key "horizontal". Uses the pairs A and D, Left and Right, and left and right on the joystick. Priority is in the same order.
engo.Input.RegisterAxis("horiztonal", AxisKeyPair{A, D}, AxisKeyPair{Left, Right}, AxisJoystickPair{LeftDirection, RightDirection})

// Register a button with key "action". Maps to space and the joystick a button. Priority is in the order they are defined.
engo.Input.RegisterButton("action", Space, JoystickA)
```

Anyway: Discuss below. I'm happy to answer questions and would love some feedback.

**Comment by paked** [comment]
DERP. ACCIDENTAL SUBMIT...

**Comment by paked** [comment]
# Input Proposal

Our current input "system" (hint: it isn't an ECS system) has been the way it is for a solid two years now. As the the rest of the engine has evolved, input seems to have remained relatively static. This is probably a good thing, at least we implemented something right the first time! However, I'd like to propose a few changes which I think will greatly improve interacting with input with Engo.

We've recently been looking at bringing Engo to new platforms: #243 (Universal Windows Platform), #247 (Web), #63 (Mobile). With the introduction of these new platforms we are now able to investigate new forms of input like joysticks and touch. I feel the current input API is a bit too brittle to make games in this fashion.

Hypothetically, I have a game which I want to release onto my Xbox and Mac/Windows/Linux. In this game my player walks around the world (which is really god damn pretty because of all the cool work @EtienneBruines has done on the rendering). Currently, this would look like this:

```go
if engo.Keys.Get(engo.W).Down() || engo.Joystick.Get(engo.UpDirection).Down() {
    space.Position.Y -= speed * dt;
}

if engo.Keys.Get(engo.S).Down() || engo.Joystick.Get(engo.DownDirection).Down() {
    space.Position.Y += speed * dt;
}

if engo.Keys.Get(engo.A).Down() || engo.Joystick.Get(engo.LeftDirection).Down() {
    space.Position.X -= speed * dt;
}

if engo.Keys.Get(engo.D).Down() || engo.Joystick.Get(engo.RightDirection).Down() {
    space.Position.X += speed * dt;
}

if engo.Keys.Get(engo.Space).Down() || engo.Joystick.Get(engo.AButton) {
    playerComponent.CheckForItem()
}
```

I propose that we have an API which looks something like the following:

```go
vert := engo.Input.Axis("vertical")
space.Position.Y += vert.Value() * speed * dt

hori := engo.Input.Axis("horizontal")
space.Position.X += hori.Value() * speed * dt

if engo.Input.Button("action").Down() {
    playerComponent.CheckForItem()
}
```

Basically what we have here is a new input system based off of `Axis` and `Button` types.

``go
type Axis interface {
    Value() float32 // A value from -1.0 to 1.0 representing the state of an
                    // axis. For a joystick the value will change depending on how far it has been
                    // pushed in a certain direction. For a key, it will be 1 if the first
                    // element of a pair is pressed, 0 if nothing is pressed and -1 if the second
                    // value of the pair is pressed.
    Pairings() []AxisPair
}

type Button interface {
    Down() bool
    JustPressed() bool
    JustReleased() bool
    Pairings() []Key
}

```

Before you use an Axis or button you have to register it:

```go
// Register an axis with key "vertical". Uses the pairs W and S, Up and Down, and up and down on the joystick. Priority is in the same order.
engo.Input.RegisterAxis("vertical", AxisKeyPair{W, S}, AxisKeyPair{Up, Down}, AxisJoystickPair{UpDirection, DownDirection})

// Register an axis with key "horizontal". Uses the pairs A and D, Left and Right, and left and right on the joystick. Priority is in the same order.
engo.Input.RegisterAxis("horiztonal", AxisKeyPair{A, D}, AxisKeyPair{Left, Right}, AxisJoystickPair{LeftDirection, RightDirection})

// Register a button with key "action". Maps to space and the joystick a button. Priority is in the order they are defined.
engo.Input.RegisterButton("action", Space, JoystickA)
```

Anyway: Discuss below. I'm happy to answer questions and would love some feedback.

**Comment by otraore** [comment]
I like it, I do recommend the core package then has some defaults registered in it so you can use the defaults for casual games and not have to force the users to do it themselves if they don't want to. So something like ```core.DefaultInput()``` or something like that. I know the name's crude but I hope the idea got across.

**Comment by paked** [comment]
@otraore Yep! I was going to have some reasonable defaults available.

I was actually anticipating that this would be apart of `engo` as opposed to `core` as it has to do with `input`, one of the topics that we said would belong there.

**Comment by otraore** [comment]
@paked Sure, I just read the gitter chat. It's a really nice idea though.

**Comment by otraore** [comment]
Closed by https://github.com/EngoEngine/engo/issues/258
