### ISSUE TITLE
Spritesheet has multiple textures

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#253]
It would be nice if a spritesheet would just load one texture onto the GPU, and simply change the view. 

But I'm not sure if that's exactly what @Newbrict is trying to achieve at the moment?

**Comment by otraore** [comment]
I'm not sure I understand this, can you explain further @EtienneBruines

**Comment by Newbrict** [comment]
isn't that exactly how the behavior is right now?

**Comment by EtienneBruines** [comment]
Currently, spritesheets:
* Are one image file
* Include multiple "images" (usually in some kind of grid)
* You can define the location of those images (within the bigger image) to use them
* But *currently* these smaller regions, get sent to the GPU one-by-one, resulting in many `GPU Texture`s. A (better) alternative is to send it to the GPU once, resulting in one big `GPU Texture`. Then you would specify the offset in the `Viewport()` method, and you're done.
