### ISSUE TITLE
AudioSystem on Web

### ISSUE THREAD

**Issue by paked** [EngoEngine/engo#256]
This is a companion issue to #174.

**Comment by mewmew** [comment]
Why the bug label?

**Comment by otraore** [comment]
Fixed @mewmew

**Comment by mewmew** [comment]
> Fixed @mewmew

Thanks. Could you remove the bug label from #174 as well?

**Comment by otraore** [comment]
@mewmew I removed and re-added because I'm not sure if it isn't a bug. Windows is a "supported platform" at the moment and audio not working on it is a bug in my opinion.

**Comment by mewmew** [comment]
> @mewmew I removed and re-added because I'm not sure if it isn't a bug. Windows is a "supported platform" at the moment and audio not working on it is a bug in my opinion.

Sounds reasonable.

**Comment by mewmew** [comment]
Before implementing this, take a look at https://github.com/hajimehoshi/ebiten/blob/master/audio/internal/driver/driver_js.go to see how it solves audio playing for the JS backend.

**Comment by otraore** [comment]
I already have a more higher level way of doing it @mewmew Thanks for the pointer though, might be useful.

**Comment by otraore** [comment]
Closed in favor of: https://github.com/EngoEngine/engo/issues/272
