### ISSUE TITLE
Documentation of public API

### ISSUE THREAD

**Issue by mewmew** [EngoEngine/engo#261]
Before the v1.0 release, the documentation of the public API of `engo` (and `core`) could use some love <3

This issue mirrors the one tracking `ecs` documentation at https://github.com/EngoEngine/ecs/issues/2

In particular, all exported functions, types, global variables, constants and methods should have a doc comment (of course using the conventions described in https://blog.golang.org/godoc-documenting-go-code).

Adding API examples would also be great (https://blog.golang.org/examples). If these were made runnable somehow from within the browser (using the GopherJS backend) that would be simply wonderful. I recon this may not be possible, but definitely worth investigating what the godoc sandbox allows and makes possible.

A more extensive package doc comment could be added to describe how the `engo` engine leverages the ECS paradigm to provide a set of core `System`s and `Component`s for implementing commonly used concepts in games.

This issue is related to the doc comment of the code. A separate issue could track the tutorial series and the concept explanations provided on engo.io.

**Comment by otraore** [comment]
I put the on-hold label because this is one of those last few issues we deal with before 1.0. Upcoming PRs and changes will try to document anything they add in, but anything left at the end will be swooped in by this one.

**Comment by otraore** [comment]
Update: Working on this
