### ISSUE TITLE
Rotate around center

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#265]
Currently we're rotating around the origin, like in the rotation demo. But it'd be cool if we could rotate around the center of the object as well. The user would define which of the two they'd like. 

Up for grabs.

**Comment by EtienneBruines** [comment]
Previously, we used the `Anchor` `engo.Point` for that. Makes sense to implement such a thing.

**Comment by Yakud** [comment]
What about this issue? This will really help to me.

**Comment by EtienneBruines** [comment]
As the original poster of this issue (and as someone who is working more than I can take), maybe this will help. 

The `modelMatrix` we're filling here, is used by OpenGL/GPU to render the objects. 

```go
        ...
	if space.Rotation != 0 {
		sin, cos := math.Sincos(space.Rotation * math.Pi / 180)

		s.modelMatrix[0] = ren.Scale.X * cos
		s.modelMatrix[1] = ren.Scale.X * sin
		s.modelMatrix[3] = ren.Scale.Y * -sin
		s.modelMatrix[4] = ren.Scale.Y * cos
	} else {
		s.modelMatrix[0] = ren.Scale.X
		s.modelMatrix[1] = 0
		s.modelMatrix[3] = 0
		s.modelMatrix[4] = ren.Scale.Y
	}

	s.modelMatrix[6] = space.Position.X
	s.modelMatrix[7] = space.Position.Y

	engo.Gl.UniformMatrix3fv(s.matrixModel, false, s.modelMatrix)

	engo.Gl.DrawElements(engo.Gl.TRIANGLES, 6, engo.Gl.UNSIGNED_SHORT, 0)
}
```
Source: https://github.com/EngoEngine/engo/blob/master/common/render_shaders.go#L216-L237

Playing around with those, might be enough to 'fix' this issue. This has to be done for every shader (there aren't that much of those), and preferably done with a settings option or a `Anchor engo.Point` as mentioned above. 

Good luck to anyone willing to participate. :-) I may be able to answer questions when `@mentioned`.

**Comment by Yakud** [comment]
@EtienneBruines Thanks for answer. Yesterday i am found another solution. For rotate sprite around anchor point i create two entities. First like body. Second like sprite. Sprite entity have a `Anchor engo.Point`. Each step I update sprite position relatively body. I am use this formula, pseudocode:
```
sprite.Rotation = *DEGRESS*
sin, cos := math.Sincos(sprite.Rotation * math.Pi / 180)
sprite.Position.X = body.Position.X - sprite.Anchor.X*cos + sprite.Anchor.Y*sin
sprite.Position.Y = body.Position.Y - sprite.Anchor.Y*cos - sprite.Anchor.X*sin
```
This code ignore sprite scale, but today i fix this. I don't know about performance of my solution. Maybe solution with shaders will work faster.

**Comment by Noofbiz** [comment]
Was fixed here https://github.com/EngoEngine/engo/pull/479.  Center now adjusts for the rotation of the space component.  To get rotation about the center, save the current center point, rotate, and then set the center to the old center point.
