### ISSUE TITLE
AudioSystem Proposal

### ISSUE THREAD

**Issue by otraore** [EngoEngine/engo#272]
We've decided to create a new audio package `engo.io/audio` which is similar to `engo.io/gl` being a wrapper around the audio players for each platform. It'll have a higher level API similar to https://godoc.org/golang.org/x/mobile/exp/audio. After it's done the AudioSystems will be using it to provide a cross-platform audio player/system. This will also attempt to support the AudioSystem on both the web and windows targets.

**Comment by otraore** [comment]
Going to give a shot at windows audio using: https://bitbucket.org/StephenPatrick/go-winaudio/src

**Comment by otraore** [comment]
Update: I've been working on windows audio using [this branch/pr](https://github.com/EngoEngine/audio/pull/3). I've got it to work using another wav file other than the previous `birds.wav` file. Setting the volume isn't properly working either. It is playing on windows though. I'm using the build in audio package demo to test it out. I'll update this PR as progress occurs.

**Comment by Noofbiz** [comment]
Closed in #494
