### ISSUE TITLE
Controls for Mobile

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#275]
I was wondering, what kind of Controls we'd like to support for our `mobile` version? Not sure if we have access to the (physical) volume buttons, or if we want to use rotation? (Not sure if we can with Android NDK/iOS)

Touch screen would obviously be one of them, but I'd think that'd be more like a mouse than like anything else. 

Ideas? Thoughts? Wishes?

**Comment by paked** [comment]
I think at this point I would be satisfied with multi-touch working.

**Comment by EtienneBruines** [comment]
This requires us to have multiple `Mouse` objects available to users.

We could change `Input.Mouse` from `Mouse` to `[]Mouse`, or add something like `Input.MouseSecondary`, `input.MouseTertiary`. But that might feel weird as it's only being used to support multi-touch. 

We could always add `input.Touch` which is an array, and let the user work with that (completely separated from `Mosue`). 

Thoughts?

**Comment by Noofbiz** [comment]
Gomobile actually already has multi-touch built in, we could just expose the Sequence to the end user somehow and they can choose how to deal with it? 

`type Event struct {
    // X and Y are the touch location, in pixels.
    X, Y float32

    // Sequence is the sequence number. The same number is shared by all events
    // in a sequence. A sequence begins with a single TypeBegin, is followed by
    // zero or more TypeMoves, and ends with a single TypeEnd. A Sequence
    // distinguishes concurrent sequences but its value is subsequently reused.
    Sequence Sequence

    // Type is the touch type.
    Type Type
}`

**Comment by Noofbiz** [comment]
I think we can keep updating the `Input.Mouse` when touch events are detected. This will allow systems designed to work with a mouse to work with touches on mobile. However, I think we should add a separate `Input.Touch` as well, so the user can design systems that use multi-touch. We could even implement it on glfw and js for touch screen devices that use those.

**Comment by Noofbiz** [comment]
Closed by #535
