### ISSUE TITLE
No mouse button demo

### ISSUE THREAD

**Issue by akiross** [EngoEngine/engo#278]
In the mouse demo there is no code showing how to deal with mouse clicks.
I suggest to introduce some code that prints different messages depending on the mouse button pressed and whether the mouse pointer was over or outside the entity.

**Comment by paked** [comment]
Once we have #276 merged in we should come up with an input demo.

**Comment by otraore** [comment]
Closed by https://github.com/EngoEngine/engo/pull/276

**Comment by EtienneBruines** [comment]
I have to disagree, not closed by #276 - since the demo in #276 doesn't use any mouse buttons.

**Comment by jrmiller82** [comment]
Yes, this is definitely needed. There needs to be a mouse-button click demo, and maybe a dragging tutorial as well.

**Comment by Noofbiz** [comment]
I've actually got a bunch of things written for that already here

https://github.com/Noofbiz/MouseTests

I could flesh it out more, get rid of the canvas stuff and replace it with dragging and deltas for the drags. 
How does that sound?

**Comment by jrmiller82** [comment]
Cool. I'll take a look at it when I get a chance. We can clean it up and make a few more demos to help out the people learning. :)
