### ISSUE TITLE
JustPressed issued after releasing long-pressed key

### ISSUE THREAD

**Issue by akiross** [EngoEngine/engo#279]
Edit (@otraore): As mentioned by @mewmew this is a https://github.com/glfw/glfw/issues/747 issue.
In the following example code, `JustPressed` should return true only when the space key is pressed. However, it yields an unexpected (or, at least, counter-intuitive) result in a specific use case.
- press and release space: outputs message once (expected)
- press and release space multiple times: outputs one message per time (expected)
- long press space key: outputs message on press **and on release (unexpected)**

Can you confirm this behavior?

``` go
package main

import (
    "engo.io/ecs"
    "engo.io/engo"
    "fmt"
)

const ActionButton = "action"

type KeySystem struct{}

func (self *KeySystem) New(w *ecs.World)  {}
func (*KeySystem) Remove(ecs.BasicEntity) {}
func (self *KeySystem) Update(dt float32) {
    if engo.Input.Button(ActionButton).JustPressed() {
        fmt.Println("Space pressed")
    }
}

type TestScene struct{}

func (*TestScene) Type() string { return "Game" }
func (*TestScene) Preload() {
    engo.Input.RegisterButton(ActionButton, engo.Space)
}

func (*TestScene) Setup(world *ecs.World) {
    world.AddSystem(&KeySystem{})
}

func main() {
    opts := engo.RunOptions{
        Title:          "Testing bug",
        Width:          400,
        Height:         400,
        StandardInputs: true,
    }
    engo.Run(opts, &TestScene{})
}
```

**Comment by nitya-dev** [comment]
Failed to replicate the behavior on linux, long press behaves as expected. 

Platform specific issue, glfw issue ? If it is still up when I get a windows or mac box to mess with I will try again.

**Comment by otraore** [comment]
Failed to replicate the behavior on OSX,  long press behaves as expected. Can someone confirm this?

**Comment by akiross** [comment]
I'm on Linux, Fedora 23, kernel 4.4.9. Please, ask if you need to know specific library versions.

I just updated engo (go get -u) and the issue remains.

**Comment by nitya-dev** [comment]
Can you supply xorg and go version ? And I guess your running default gnome 3, up-to-date ? I will boot up a fedora image later today and test there, still unable to replicate it on Manjaro with KDE.

go version go1.6.2
Linux 4.4.11 x86_64 
X.Org X Server 1.17.4

To be clear I copied your sample, run it and hold down space at start for 2-5-10 seconds and only one message shows after releasing the space bar. Tried a few other key combo's but none of them show the second message when holding the key down for a while.

**Comment by akiross** [comment]
X.Org X Server 1.17.2
Version 3.18.2
go version go1.5.4 linux/amd64
Yes, I keep the system up to date (as far as the distro allows)

If you press the space key, you should see "space pressed" immediately after pressing, but you should not see anything (new) after releasing. In my case, I *do* see something new after a long-press release, but I don't see anything new after a short-press (<1s) release.

So, after run-press-long_wait-release, I see two "space pressed" messages (one when pressing, one when releasing).
After run-press-release, I see one "space pressed" message (only when pressing).

**Comment by nitya-dev** [comment]
This seems to be related to https://github.com/glfw/glfw/issues/747, when adding logs to the glfw callback and enabling/disabling swapbuffer I get the same results as mentioned in the last post there.

I'm unable to trace down the fix but it feels like and upstream issue that got fixed, manjaro packages are a head of fedora so wait till fedora patches x11 to 1.17.3/4 or higher and check again ?

If that is the case the glfw issue on arch should be solved as well, I might confirm that when I find the time and will to install an arch image.

**Comment by Noofbiz** [comment]
This issue was with GLFW and has been fixed as far as I can tell.
