### ISSUE TITLE
Better Tests 

### ISSUE THREAD

**Issue by otraore** [EngoEngine/engo#284]
Although there's a lot of things we can't really do unit tests on, there's a lot of places we could place better tests or entirely new ones. Up for grabs.

**Comment by otraore** [comment]
I wanted to suggest maybe we should create smaller issues on top of this big one, so right now I was browsing #335 and I thought there should be a test on our tilemap system seeing if a dummy date's tilename attribute matches etc. So it made sense to create a small issue addressing this rather than small PRs contributing to this one. It'd make for smaller bite-sized issues rather than gigantic issue that might scare off some people. The cons I can think of is our issue count going up. Although when you have smaller issues like that, makes it easier to tackle so eventually I think the issue count should go down. Thoughts?

**Comment by EtienneBruines** [comment]
> Thoughts?

I would say we do this "on the fly", adding stuff as we come to think of it. Creating an issue for each new specific useful test we want to add; or just adding code together with other commits like it's the same as fixing a typo.

**Comment by otraore** [comment]
So if I understand right we agree, Anyone else want to express their thoughts on this?

**Comment by paked** [comment]
I also agree that this sort of thing is probably more elegantly handled on a case-by-case basis.

I'm going to close this now. Please start making issues for your specific problems.
