### ISSUE TITLE
Add code coverage reporting to Travis CI

### ISSUE THREAD

**Issue by mewmew** [EngoEngine/engo#295]
(Creating dedicated issue for tracking this work. Comment originally posted in https://github.com/EngoEngine/engo/issues/117#issuecomment-213408780)

The Travis config may be extended to report the lint status of the project. For an example project using this approach, refer to the following `goclean.sh` script and travis config:

* [goclean.sh](https://gist.github.com/mewmew/379014c9a2e6885e238d) (which is a fork of https://gist.github.com/h12w/0f22736320abe6be71ce).
* [.travis.yml](https://github.com/mewkiz/flac/blob/master/.travis.yml)

The `goclean.sh` script reports issues from `gofmt`, `goimports`, `golint`, `go vet`, `go test -race` and `go cover`.  Test coverage is optionally reported to https://coveralls.io/.

Note, the `secure` environment variable is an encrypted version of the `COVERALLS_TOKEN` environment variable. For a howto, see https://github.com/decomp/decompilation/issues/4#issuecomment-62314749.

**Comment by paked** [comment]
> Harrison Shoebridge @paked 21:09
> @otraore Is this [coveralls] done: EngoEngine/engo#295 
> I've seen coveralls around the place, so I assume so?
> 
> Ousmane Traore @otraore 21:09
> It is done BUT
> there’s an issue on coveralls side and our badge
> as for reporting it’s done in the PR and the page as well
> But this is a bug others are experiencing as well.
> So you can close the issue.
