### ISSUE TITLE
Write a Tutorial about Animation

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#30]
The wiki is an excellent place for extra information than the demos offer. 

@matiwinnetou offered to do this for the Animation. 

( [Animation Wiki](https://github.com/paked/engi/wiki/Animation) )

**Comment by matiwinnetou** [comment]
Yes I will take this. You can assign me, since I cannot do this myself

**Comment by paked** [comment]
@matiwinnetou I don't think I can assign you if you aren't a collaborator on the repo

**Comment by EtienneBruines** [comment]
@paked you are [correct](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/).

**Comment by matiwinnetou** [comment]
thx for assigning me I will finish this soon.

**Comment by paked** [comment]
This will be handled in the EngoEngine tutorial series on our website.
