### ISSUE TITLE
canvasWidth, canvasHeight bug

### ISSUE THREAD

**Issue by otraore** [EngoEngine/engo#300]
> The issue is https://github.com/EngoEngine/engo/blob/master/engo_glfw.go#L111
> Removing it and going back to the old implementation fixes the bug
> But will undo the work done to support retina displays
> This currently affects OSX
> It might affect other desktop platforms as well
-@otraore gitter chat

issue discovered by @Glorfunkel

**Comment by EtienneBruines** [comment]
https://github.com/EngoEngine/engo/blob/master/engo_glfw.go#L111

Fix `canvasWidth, windowWidth` to `canvasWidth, canvasHeight`.

**Comment by otraore** [comment]
Sure
