### ISSUE TITLE
Try out iOS

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#306]
Someone with an iPhone and XCode should try to run it. 

I've read/heard that `ios` is _not_ the build-tag for iOS. Instead you use `amd64 darwin` (note the space in between). If we were to use that, maybe we could get it to build. 

Up for grabs.

**Comment by otraore** [comment]
Grabbing later in the day

**Comment by EtienneBruines** [comment]
Be sure to share your findings at gitter :smile:

**Comment by otraore** [comment]
Update we got it to build. Sadly I wasn't able to test it out on the emulator. We think it's because of https://github.com/golang/go/wiki/Mobile#ios-simulator . This might differ on a iOS device.

**Comment by paked** [comment]
Do we need to find someone with an iOS device in order to continue testing?

**Comment by otraore** [comment]
Believe so, or I can set up the simulator for it according to x/mobile's suggestions

**Comment by paked** [comment]
@otraore How did this go?
