### ISSUE TITLE
Multiple sounds at once

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#307]
Our current `AudioSystem` is limited to one simultaneous audio fragment. It makes sense to have multiple audio sources playing at the same time (i.e. sound effects from different sources). 

Marking this as "bug" because this "limitation" is not documented, nor assumed. 

@otraore Is this something you want to take on? (since you're working on `engo.io/audio`? Or would you rather that I?)

**Comment by Noofbiz** [comment]
Closed in #494
