### ISSUE TITLE
Add images/diagrams to the Camera Tutorial

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#31]
I think the tutorial about the Camera would benefit from diagrams / images showing objects in some 2d-plot. 

This is quite some effort, so I'd say this is low-priority (you can label it as such). 

( [Camera Wiki](https://github.com/paked/engi/wiki/Camera) )

**Comment by matiwinnetou** [comment]
@EtienneBruines I looked at your tutorial, this is awesome work!!!

**Comment by paked** [comment]
:+1: for @EtienneBruines

**Comment by paked** [comment]
We no longer have a "camera" tutorial.

**Comment by EtienneBruines** [comment]
We do, but it's outdated. See https://github.com/EngoEngine/engoengine.github.io/issues/17
