### ISSUE TITLE
engo.Point{}.Within 

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#313]
@otraore thought it'd be nice to be able to say

```go
point := engo.Point{1, 2}
spaceComponent := common.SpaceComponent{
    Position: engo.Point{3, 4},
    Width: 5,
    Height: 6,
}

// Specifically this line:
point.Within(spaceComponent)

// This you can already do, and should result in exactly the same:
spaceComponent.Within(point)
```

**Comment by mewmew** [comment]
How do we make `Point` not depend on the `common` package? Through an interface?

If we define a method `Within` on point, it would make sense to rename the `SpaceComponent.Within` method to `Contains`. Perhaps that's just a personal preference. What do you think?

**Comment by EtienneBruines** [comment]
> How do we make Point not depend on the common package? Through an interface?

You're right, we can't. (interface doesn't really make it any better, at least not for a "convenience" method, imho)

`Contains` SGTM. Awaiting response from others :smile:

**Comment by otraore** [comment]
> https://github.com/EngoEngine/engo/issues/313#issuecomment-220161908
> That’s the rename we were looking for. @mewmew
> Contains does make a lot more sence for a space component
> And Within more sense for a Point
> @otraore in the gitter chat

**Comment by EtienneBruines** [comment]
> Harrison Shoebridge @paked 23:27
> Yep!
> That's what I was trying to say

**Comment by EtienneBruines** [comment]
Up for grabs.

**Comment by paked** [comment]
Closes by #333

**Comment by otraore** [comment]
I disagree @paked because https://github.com/EngoEngine/engo/pull/333 only fixes one of the things mentioned in this issue. The other one `Poing.Within` is still up for grabs. It's a tough issue.

**Comment by mewmew** [comment]
> > How do we make Point not depend on the common package? Through an interface?
>
> You're right, we can't. (interface doesn't really make it any better, at least not for a "convenience" method, IMHO)

> The other one Poing.Within is still up for grabs. It's a tough issue.

@otraore, could you elaborate? I thought we were not going to add a `Within` method to `Point`, as that would require it to have knowledge about `common`. Or are we aiming to introduce some form of interface to encapsulate the notion of an entity in which another entity may be contained within?

One option may be.

```go
package engo

// A Container is a 2-dimensional closed shape which may contain a set of points.
type Container interface {
   // Contains reports whether the container contains the given point.
   Contains(p Point) bool
}

// A Point is an X, Y coordinate pair. The axes increase right and down.
type Point struct {
   // X- and y-coordinates.
   X, Y int
}

// Within reports whether the point is contained within the given container.
func (p Point) Within(c Container) bool {
   return c.Contains(p)
}
```

```go
package common

// A Rectangle contains the points with Min.X <= X < Max.X, Min.Y <= Y < Max.Y.
type Rectangle struct {
   // Top-left and bottom-right corner of the rectangle.
   Min, Max engo.Point
}

// Contains reports whether the container contains the given point.
func (r Rectangle) Contains(p engo.Point) bool {
   return r.Min.X <= p.X && p.X < r.Max.X && r.Min.Y <= p.Y && p.Y < r.Max.Y
}

// A Circle represents 
type Circle struct {
   // Centerpoint of the circle.
   Origin engo.Point
   // Radius.
   Radius int
}

// Contains reports whether the container contains the given point.
func (c Circle) Contains(p engo.Point) bool {
   // sqrt(dx^2 + dy^2)
   dx := math.Abs(c.Origin.X - p.X)
   dy := math.Abs(c.Origin.Y - p.Y)
   // NOTE: Should it be `hypo < c.Radius` or `hypo <= c.Radius`?
   return math.Sqrt(math.Pow(dx, 2), math.Pow(dy, 2)) < c.Radius
}
```

Looking at the `image` package of the Go standard library, I believe we should change the name from `Within` to `In`:

```go
// In reports whether p is in r.
func (p Point) In(r Rectangle) bool
```

(The above code has not been tested or compiled, just included to spark a discussion)

**Comment by mewmew** [comment]
On a side node, may I ask why we are not reusing (and potentially extending through embedding) the already defined `image.Rectangle` and `image.Point`?

**Comment by otraore** [comment]
@mewmew In response to your first suggestion, that seems like a really nice solution. I'm going to implement it and send in a PR to spark up a discussion.
