### ISSUE TITLE
Interfaces within Systems

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#316]
I think it's time for the next big thing. 

Take the following code ([here](https://github.com/EngoEngine/engo/blob/master/common/render.go#L69-L73) and [here](https://github.com/EngoEngine/engo/blob/master/common/render.go#L120-L121)): 
```go
type renderEntity struct {
	*ecs.BasicEntity
	*RenderComponent
	*SpaceComponent
}

func (rs *RenderSystem) Add(basic *ecs.BasicEntity, render *RenderComponent, space *SpaceComponent) {
    rs.entities = append(rs.entities, renderEntity{basic, render, space})
}
```

Wouldn't it be awesome to have it look like this?

```go
type Renderer interface {
    // Note we'll have to find nice names for these
    ecs.Entitier 
    RenderComponenter
    SpaceComponenter
}

func (rs *RenderSystem) Add(r *Renderer) {
    rs.entities = append(rs.entities, r)
}
```

We would then define both the `Component`, as the `interface` for that `Component`, which would result in a bit more verbose code (because of all the getters and setters). And there might be a problem with conflicting names of methods. 

Some of you have brought up this idea a few weeks ago already, but I think we're ready to have a discussion about that here :smile: 

(Milestone 1.0 was added because this is an "do or don't before 1.0")

**Comment by paked** [comment]
@EtienneBruines Would you mind expanding on the benefits of this?

**Comment by EtienneBruines** [comment]
The benefits of this would be:

1. You don't need to reference every component required within the `Add` method. 
2. You don't have to worry about the order of the things you're referencing. 
3. Looks pretty cool (except for the definition of the getters/setters)
4. No one has to guess what a `renderEntity` or whatever is, because it's an interface - everyone'll understand it. See #241 for an example where this was an issue (pun not intended).

**Comment by EtienneBruines** [comment]
I'm going to be honest here :smile: 

I dislike it, but it might still be worth the discussion, depending on what others feel. 

The reason for disliking it:

* Our `common` codebase becomes more unreadable. 
* It feels like an abuse of the go `interface`. Since we're not really requiring any methods, and to define interfaces for everything just to implement them once, doesn't make much sense either.

**Comment by mewmew** [comment]
> It feels like an abuse of the go interface. Since we're not really requiring any methods, and to define interfaces for everything just to implement them once, doesn't make much sense either.

My thoughts exactly. Thank you for summing them up! I had been meaning to write a reply after evaluating this in more detail, but I am strongly against defining interfaces just for the reason of defining interfaces. Pre-mature abstractions are just as dangerous as pre-mature optimization. In the future, if several `RenderComponent`s (or some other component) have been defined, then we may create an interface which encapsulates their shared behaviour. It is of course interesting to have a discussion about these topics nonetheless, but to make a decision in favour of interfaces we would really need some concrete *real-world* implementations of the interface, to justify its existence.

Thanks for bringing it up to discussion. We can definitely keep this in mind for the future.

**Comment by Newbrict** [comment]
Thanks for the mention. I've reviewed the comments and I am against it for one reason.
 - Harder to read makes it harder for new people to get into the codebase

**Comment by otraore** [comment]
By popular decision from all those myself and all those above me. I am closing this until further notice. We can always revisit this should we need to. Thanks for bringing up the idea @EtienneBruines.
