### ISSUE TITLE
Delta time broken on start up / long pauses

### ISSUE THREAD

**Issue by nitya-sattva** [EngoEngine/engo#325]
When updating the clock I removed a check that prevented a large delta in to clock when there is allot of loading and setting up before the main loop starts. (Forgot the clock in engo was initialized before loading assets)

I dislike the idea of adding that check back in to the tick method. It could be solved by initializing the clock right before the main loop starts or by adding a call to a reset method on the clock. (like the links down below)

https://github.com/nitya-sattva/engo/commit/66fd4714cbac4f0a2fb9b643480ef074ac5e183b
https://github.com/nitya-sattva/engo/commit/dbec1e116238f69288baad4120284c8f78788731

There are a few other cases when a rest might be preferred. Example some systems will block the render thread when dragging the window around, a reset when the user stops moving the window would avoid a jump in logic and/or animations.

I'm not sure about web and mobile, needs some insight.

**Comment by EtienneBruines** [comment]
Wouldn't this solve it as well?

```go
	if secondsInNano <= c.elapsStamp {
		c.elapsStamp %= secondsInNano
		c.perSecond = c.counter
		c.counter = 0
	}
```

to

```go
	for secondsInNano <= c.elapsStamp {
		c.elapsStamp %= secondsInNano
		c.perSecond = c.counter
		c.counter = 0
	}
```

This would result in an FPS of `0` during startup, but that's accurate.

**Comment by paked** [comment]
> When updating the clock I removed a check that prevented a large delta in to clock when there is allot of loading and setting up before the main loop starts. (Forgot the clock in engo was initialized before loading assets)

Thoughts on just fixing this problem at the root? We could just start the clock once preloading finishes and the initial scene begins?

**Comment by EtienneBruines** [comment]
@paked But that wouldn't solve the problem when lag occurs (and more than 2 seconds pass).

**Comment by nitya-sattva** [comment]
@EtienneBruines No the 'if' to 'for' would not fix the delta time, if the fps indicates a lag spike that would be fine in my mind.

Old code
```
if !c.frame.IsZero() {
  c.delta = float32(now.Sub(c.frame).Seconds())
}
```
That prevent delta from being set, but that is a branch that is only needed at start up but would run every frame. In the new code without the check 'frameStamp' needs to be as close to current time as possible on the first frame, after some lag spikes (not all). If that is the case the delta time should be acceptable.

@paked My initial thought as well, but it is just a patch sins there are other reasons that might require a reset and using Time.Time() to see how long it took to load is also handy.

**Comment by nitya-sattva** [comment]
Should be fixed: https://github.com/EngoEngine/engo/pull/327
