### ISSUE TITLE
Uncaught Error: no `FileLoader` associated with this extension: ".wav" in url "sfx/crash.wav"

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#326]
On `netgo`, it does not register the `.wav` extension, causing everything to crash. 

Would be nicer if it would register a `.wav` FileLoader, which did "nothing" (maybe log what he should've done, or that it's not yet implemented)

This isn't needed when audio is fixed (#272), but till then, this is a nice-to-have feature.

**Comment by paked** [comment]
What about a generic file loader which does "nothing", every resource that does not have an existing loader assigned to it will get sent to it. From there we could log/panic/handle the exception appropriately.

**Comment by EtienneBruines** [comment]
> From there we could log/panic/handle the exception appropriately.

We already can do these things, we don't need a generic file loader for that? :wink:

**Comment by Noofbiz** [comment]
Closed in #494
