### ISSUE TITLE
Add vendoring recommendations for people concerned with stability

### ISSUE THREAD

**Issue by paked** [EngoEngine/engo#334]
As a result of the discussion of #286 we have decided that we will be following the lead of Azul3D and not specifically vendoring Engo. Instead it will be up to the users to vendor and manage which version of Engo they want to use in their project. This allows people to quickly submit a feature request, have it fulfilled, and then use it in their game project as soon as possible.

More technically described in this comment: https://github.com/EngoEngine/engo/issues/286#issuecomment-218421303

This issue is closed by adding a short section further describing this near the top of the README.

**Comment by otraore** [comment]
I like this idea, as for recommendations I'd recommend [glide](http://glide.sh/) (what I use for some internal projects, feels a lot like bundler) or [Godeps](Personally prefer glide over it but Godeps is really popular amongst a lot of projects. Also you should mention in the issue that the users can also vendor external packages.

**Comment by solf1re2** [comment]
While not official yet, will this vendoring be re-assessed when/if [https://github.com/golang/dep](https://github.com/golang/dep ) becomes the standard and integrated into the go toolchain?

**Comment by paked** [comment]
@solf1re2: Yes, we'll of course defer to any toolchain decisions the Go team make.

**Comment by otraore** [comment]
I feel like a good way to go would be to mention that it'll be up to them to vendor their packages and just suggest a few popular tools (glide, godeps, dep) and leave it up to them to decide. It's not up to us to choose one for them.

**Comment by Noofbiz** [comment]
vgo was recently announced, info here https://research.swtch.com/vgo-intro I'll play around with it at some point and see when we should try using it

**Comment by Noofbiz** [comment]
go 1.11 has support for vendoring built-in! I'll update this to use go modules for v1.1 ^_^
