### ISSUE TITLE
Wrong return from line intersection

### ISSUE THREAD

**Issue by hydroflame** [EngoEngine/engo#339]
https://github.com/EngoEngine/engo/blob/master/math.go#L214-L231

minimum return NaN NaN

**Comment by paked** [comment]
@clebs Feel free.

I'll definitely accept the PR for this.

**Comment by clebs** [comment]
Hi @paked, I already created a PR for this.
It would be great to get feedback on it.
Thanks!

**Comment by otraore** [comment]
Closed by #397
