### ISSUE TITLE
Input Demo - This is broken on web builds

### ISSUE THREAD

**Issue by ghost** [EngoEngine/engo#342]
When running the input demo in the browser this almost never fires: btn.JustPressed()

Looked over the code and I think this is because the callback to 'Input.keys.Set()' might happen before 'Input.Update()' and the code expects it to be set after. (Did not verify, but seems like the only logical conclusion)

The only way around this that I can see is to create a temp buffer to store key state from the callbacks and then pass them on to 'Input.keys.Set()' after 'Input.Update()' ?

---

Edit: Buffer fix works, demo code is below. I can move it in to a pull-able branch if it is the best solution. (Branch it is in now is dirty)
- Input Demo: Better for testing
  https://github.com/nitya-dev/engo/commit/37248588d5254ab19103ec572fc741927253ca23
- Buffer keys in web build: File 'engo_js.go'
  https://github.com/nitya-dev/engo/commit/ea3b15843a60c1e050da8a9718601a6b78b7d62e#diff-a2ad628a9a250d105a8a9df7b5fe7698

**Comment by EtienneBruines** [comment]
I doubt this is only an issue on the web? I mean, the web version uses the same code as the desktop one, at least w.r.t. the input.

**Comment by paked** [comment]
If Input.keys.Set and Input.Update are performed out of order you could end
up with some weird situations. This may be the problem?

**Comment by Noofbiz** [comment]
Fixed by #492
