### ISSUE TITLE
GoDoc: Common package is missing

### ISSUE THREAD

**Issue by kylewolfe** [EngoEngine/engo#344]
https://godoc.org/engo.io/engo/ is reachable but https://godoc.org/engo.io/engo/common is not.

This is the first time I've come across this issue, so I am opening it here for research since I discovered it on this project. It could be related to the custom go get source you have or it might be related to GoDoc it's self.

**Comment by kylewolfe** [comment]
Here's a custom go get address that has sub directories listed in its GoDoc for comparison:

```
curl 0f.io/roomba
<a href="http://godoc.org/0f.io/roomba">Found</a>.

curl 0f.io/roomba/roombacmd
<a href="http://godoc.org/0f.io/roomba/roombacmd">Found</a>.
```

**Comment by otraore** [comment]
I know why it's happening, thanks for reporting @kylewolfe I'll fix it once I get home (Around an hour or so)

**Comment by otraore** [comment]
Update: I tried to give it a shot (https://github.com/EngoEngine/engoengine.github.io/commits/master) [Last 4 commits] but had little success. I'll give it another go™ tomorrow. Again thanks for bringing this to our attention

**Comment by jrmiller82** [comment]
godoc stil doesn't have common in it as of today.
