### ISSUE TITLE
Keys namespace

### ISSUE THREAD

**Issue by Sendoushi** [EngoEngine/engo#349]
As of this moment, each key is under the same general namespace. So if you want the `w` key, you would get `engo.W`.

My proposition:
Namespace so we could get it with `engo.Keys.W`. This way we wouldn't "dirty" the general namespace and it would be easier with an IDE for example to understand what that `engo.W` means.

**Comment by EtienneBruines** [comment]
SGTM. @paked @otraore ?

**Comment by paked** [comment]
SGTM.

**Comment by otraore** [comment]
SGTM. I'll submit a PR soon if no-one does it by the time I'm free.

**Comment by Sendoushi** [comment]
Cool! I would do it but i'm on the tutorial PR ehehe

**Comment by Luukdegram** [comment]
Doing this would require to either move the keys to a new package called **keys** or create a struct called **Keys**. Personally, I'm for placing them in a new package. This way we can make them a const so users can't edit them. One thing to note is that it would become **keys.W** instead of **engo.Keys.W**

**Comment by EtienneBruines** [comment]
`engo.KeyW` is also a possibility. That way we won't have it namespaced, but it'll be clear what it is? 

> This way we can make them a const so users can't edit them. 

I would think this is something we'd want to achieve, yes.

**Comment by Luukdegram** [comment]
> engo.KeyW is also a possibility. That way we won't have it namespaced, but it'll be clear what it is?

I like this. Also makes it more 'part' of Engo, if that makes any sense.

**Comment by Sendoushi** [comment]
I still would namespace. When you `engo.` it should only show the modules, if you have there KeyA, KeyB... it will show a thousand properties. Still... It is better than not having any namespace in my opinion.

**Comment by otraore** [comment]
I think like @Sendoushi it shouldn't polute the global `engo` package but now that I think about it. If you type in `engo.Key` all the keys should pop up. This is done in the stdlib for example [here](https://golang.org/src/net/http/status.go). Instead of doing something like `status.OK` they used `http.StatusOK`. I'm personally fine with all possibilities but just giving what I think about each.

**Comment by otraore** [comment]
Bringing this issue up again, thoughts?

**Comment by Sendoushi** [comment]
I'm with my proposal `engo.Key.W`.

**Comment by otraore** [comment]
I'm going to assume you meant to write engo.Keys?

**Comment by Sendoushi** [comment]
Yes. I did.

**Comment by nitya-dev** [comment]
As mentioned before, these values need to be const to avoid problems and to allow the compiler to inline them when needed. 

Golang does not provide a way to namespace const values in to `engo.Keys` as far as I know, so for me the only valid options are `Keys.W` or `engo.KeyW`. Both have there ups and downs and I'm neutral towards ether of those, I'm opposed to any solution that makes (or keeps) these values as variables.

**Comment by otraore** [comment]
For reasons mentioned by @nitya-dev I think `keys.W` or `engo.KeyW` are the best options here. Thoughts on either one? I'm leaning more towards `engo.KeyW`.

**Comment by EtienneBruines** [comment]
And as an added bonus, they would *all* be constant where possible. Instead of set within an `init` method as done in `engo_glfw.go` - we should have platform-specific `input_data.go` files IMHO.

**Comment by otraore** [comment]
I created a poll here so we can vote on either one http://goo.gl/DHniyG. Also @Sendoushi if we do use engo.Key.W that means that 'Key' would be a struct with no support for constants.

**Comment by otraore** [comment]
`engo.KeyW` it is, I'll submit a PR soon to address this.
