### ISSUE TITLE
Feature Request - Add layer information to TMX TileMaps tiles

### ISSUE THREAD

**Issue by randomandy** [EngoEngine/engo#353]
Please correct me if I'm wrong, but:

After playing around with engo for a few days now, I get the feeling that it'd be necessary for TileMaps to contain their different layer information.
That way it's possible to assign each layer's tiles (or objects, images for that matter) a specific **ZIndex** (`tile.RenderComponent.SetZIndex(x)`)

Right now engo handles TMX maps by distinguishing between **Tiles** (`TMXResource.Level.Tiles`) and **Images** (`TMXResource.Level.Images`).
So if I'm not mistaken, currently one has to range over all Tiles and Images:

```
resource, err := engo.Files.Resource("example.tmx")
if err != nil {
    panic(err)
}

tmxResource := resource.(common.TMXResource)
levelData := tmxResource.Level
```

and then:

```
for _, v := range levelData.Tiles {
    if v.Image != nil {
        tile := &Tile{BasicEntity: ecs.NewBasic()}
        tile.RenderComponent = common.RenderComponent{
            Drawable: v,
            Scale:    engo.Point{1, 1},
        }
        tile.SpaceComponent = common.SpaceComponent{
            Position: v.Point,
            Width:    0,
            Height:   0,
        }
        tileComponents = append(tileComponents, tile)
    }
}

for _, v := range levelData.Images {
    if v.Image != nil {
        tile := &Tile{BasicEntity: ecs.NewBasic()}
        tile.RenderComponent = common.RenderComponent{
            Drawable: v,
            Scale:    engo.Point{1, 1},
        }

        tile.RenderComponent.SetZIndex(2)

        tile.SpaceComponent = common.SpaceComponent{
            Position: v.Point,
            Width:    0,
            Height:   0,
        }

        tileComponents = append(tileComponents, tile)
    }
}

```

From what I understand after playing around with [Tiled](http://www.mapeditor.org/), it would make sense to distinguish between Tiles, Objects and Images.
Therefor it would be necessary that each Tile would also "know" the Tile Layer it belongs to. Same goes for Objects and Images of course.

For instance when ranging over []*common.tile in your TMXResource.Level.Tiles, maybe each element could contain the name of its tile layer:

```
for _, tile := range levelData.Tiles {
    // tile.Layer could contain the information of the tile's layer
}
```

Or maybe even better, let common.TMXResource.Level contain an array of all layers (of all types: tile layer, object layer, image layer):

```
for _, tileLayer := range levelData.TileLayers {
    for _, tile := range tileLayer {
        ...
    }
}

for _, objectLayer := range levelData.ObjectLayers {
    for _, tile := range objectLayer {
        ...
    }
}

for _, imageLayer := range levelData.ImageLayers {
    for _, tile := range imageLayer {
        ...
    }
}
```

Let me know what you think

**Comment by randomandy** [comment]
I've added a PR #354 with a very basic fix. It simply adds the layer name to the each `common.tile`. That way each tile now "knows" to which tile layer it belongs and can therefor be assigned a __ZIndex__ if necessary (to create depth)

**Comment by randomandy** [comment]
Done. See #357 

As promised, I re-wrote the entire TileMap feature in engo. It follows the idea I presented in #353, which introduces Layer support for the TMX maps in engo.

The main things are:
* Layer support for TMX TileMaps
  * Each level contains now a list of TileLayers
  * Each level contains now a list of ImageLayers
  * Each level contains now a list of ObjectLayers
* I followed the TileMap standard set by the [Tiled](http://www.mapeditor.org/) editor
  * All default Tile attributes are now supported
  * All default Image attributes are now supported
  * Objects are now supported
    * Regular objects and all their default fields are now supported
    * Polyline objects and all their default fields are now supported

Be aware that _this is a breaking change_, meaning that users will have to touch their games and update them to the new TileMap feature.
__I've updated all engo demos that used the old TileMap implementation__ and also added __a new demo__ called 'adventure', which I used to test my changes.
The new demo puts a lot of different things to use shown in many different demos, but most importantly demonstrates how to use the new layer support.

With this new implementation we now support depth in TileMaps, meaning, that we can set for instance a Z Index for different layers, to let a character entity hide behind trees, or to hide trees behind clouds.

Let me know what you think, I hope you like it ;-)

**Comment by EtienneBruines** [comment]
I'm not really a Tilemap-kinda-guy, so even though this may be great & awesome, I don't know anything about it :laughing: 

@paked @Newbrict ?

**Comment by otraore** [comment]
I am and this is a great issue/addition to our tilemap implementation @EtienneBruines
