### ISSUE TITLE
Fix instances of luxengine/math

### ISSUE THREAD

**Issue by otraore** [EngoEngine/engo#359]
https://github.com/luxengine had all it's repositories excluding `lux` deleted (We don't know why as of yet, and we received no notice of this) including one that engo depends on `math`.  This is causing all CIs to build and will mean that any newcomers who go get engo will receive an error. This is an urgent issue.

**Comment by lugorian** [comment]
It's not deleted, just moved to https://github.com/luxengine/lux/tree/master/math ...

**Comment by otraore** [comment]
Oh well I didn't see that and there was no indication of what happened
