### ISSUE TITLE
math.LineIntersection() returns {-1, -1} if there is no intersection

### ISSUE THREAD

**Issue by faiface** [EngoEngine/engo#360]
What if the two lines actually intersect at {-1, -1}?

**Comment by otraore** [comment]
Related to: [this](https://github.com/EngoEngine/engo/issues/339)

**Comment by EtienneBruines** [comment]
This is a serious issue. I have to say, I'm no math genius. And nor is any of our contributors (IIRC). Perhaps we do want to move to use `glm` for these kind of things? Or remove those methods completely?

(I know glm has been unstable quite often, but we could fork it to keep it at a non-broken version, like we did with `math`? )

Thoughts? @paked @otraore ?

**Comment by otraore** [comment]
If you can find a way to fix this using glm, by all means go ahead. I agree with forking it like we've done before with glm (before we removed it as a dependency) and math

**Comment by faiface** [comment]
Or perhaps another solution could be to rewrite those function in a way that they return multiple values, such as:

point, ok := math.LineIntersection(line1, line2)

Where ok would be true if there is an intersection, otherwise false.

**Comment by EtienneBruines** [comment]
@faiface that doesn't sound that bad. 

Although I personally wouldn't call it `point, ok` in usage, though :laughing: (because `ok` might sound a bit weird)

This would be easier to implement, I guess.

**Comment by paked** [comment]
@faiface Good idea. I like this solution.

@EtienneBruines That's actually pretty common standard library practice... But like, you could call it whatever you wanted anyway :D!

**Comment by EtienneBruines** [comment]
@paked Hmm, yeah, now to think of it, `ok` as an indicator "did the intersection pass" might not be such a bad idea. (I use `, ok`  quite often, had to get used to the idea of using it for this as well :laughing: )

**Comment by otraore** [comment]
Closed by #397
