### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by term1nal** [EngoEngine/engo#366]
In the various camera scrollers (eg: entity scroller, keyboard scroller), I've noticed that there does not appear to be steps taken to normalize the movement in the diagonal. Shouldn't this be considered as an toggle-able option to keep from diagonal movement essentially equating to 2x movement speed?

**Comment by EtienneBruines** [comment]
> Shouldn't this be considered as an toggle-able option to keep from diagonal movement essentially equating to 2x movement speed?

You make a valid point. This becomes even more important when we start supporting joysticks and such.

**Comment by Term1nal** [comment]
Like, basically, normalized movement vectors rather than incrementing the X/Y axis by speed*delta individually.

I *think* this would be the proper code snippet:

````Go
direction := Point{1, 1} //down and right

normaldirection, _ := direction.Normalize()
normaldirection.MultiplyScalar(speed * delta)

c.entity.SpaceComponent.Position.Add(normaldirection)
````

**Comment by paked** [comment]
This sounds good to me.
