### ISSUE TITLE
gomobile build -target ios fails

### ISSUE THREAD

**Issue by hajimehoshi** [EngoEngine/engo#371]
```
$ gomobile build -target ios engo.io/engo/demos/pong
gomobile: go build -p=4 -pkgdir=/Users/hajimehoshi/go/pkg/gomobile/pkg_darwin_arm -tags="ios" -o=/var/folders/7t/qw3np69559591s1v0mk5_p1m0000gn/T/gomobile-work-098991452/arm engo.io/engo/demos/pong failed: exit status 2
# github.com/go-gl/glfw/v3.1/glfw
In file included from go/src/github.com/go-gl/glfw/v3.1/glfw/cocoainit_darwin.go:6:
In file included from ./glfw/src/cocoa_init.m:27:
In file included from ./glfw/src/internal.h:63:
./glfw/src/../include/GLFW/glfw3.h:124:12: fatal error: 'OpenGL/gl.h' file not found
  #include <OpenGL/gl.h>
           ^
1 error generated.
# github.com/go-gl/gl/v2.1/gl
ld: framework not found OpenGL
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The build tags should be:
- `ios darwin,arm darwin,arm64` for iOS
- `android` for Android
- `!ios`, `darwin,!arm,!arm64` for non-iOS
- `!android` for non-Android.

as I mentioned at #370.

**Comment by fastfading** [comment]
hi  hajimehoshi  , we have email before
which go game engine is better, yours or this engo?
what block the ios build ?   gomobile supported ios,  I have successfully  gomobile build ios , and run on iphone.   But  there is something wrong to distribute it to app store

**Comment by hajimehoshi** [comment]
I don't understand your question. The situation doesn't change after you mailed

**Comment by fastfading** [comment]
which is better，   engo  or your game engine？

2017-10-13 16:31 GMT+08:00 Hajime Hoshi <notifications@github.com>:

**Comment by hajimehoshi** [comment]
I'm afraid I don't think here is the appropriate place to answer such question :-)

**Comment by Noofbiz** [comment]
Well, as far as I know, there was some reason it doesn't work on ios when you build it using gomobile. However, no one on the team has a Mac to do testing on and fix it, so for now the tags are setup on purpose to not build for ios at all. If you have time and a Mac to work on and fix it, that would be a welcome contribution!
