### ISSUE TITLE
Rename PreloadedSpriteSingle to LoadedSprite

### ISSUE THREAD

**Issue by otraore** [EngoEngine/engo#375]
I personally find `PreloadedSpriteSingle` unnecessarily long to [type](https://github.com/EngoEngine/engo/blob/master/demos/pong/pong.go#L65) [all](https://github.com/EngoEngine/engo/blob/master/demos/hello-world/hello.go#L31) [the](https://github.com/EngoEngine/engo/blob/master/demos/falling/falling.go#L47) [time](https://github.com/EngoEngine/engo/blob/master/demos/mouse/mouse.go#L41). I'm suggesting we change it to `LoadedSprite` and if we ever have a `PreloadedSpriteMultiple` we call it `LoadedSprites`. 

Thoughts?

**Comment by paked** [comment]
SGTM

**Comment by EtienneBruines** [comment]
SGTM.

**Comment by paked** [comment]
This should really just be a simple usage of `go rename`.
