### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by yarbelk** [EngoEngine/engo#376]
Add a CONTRIBUTING.md to help people know what is expected for contributing (like needing tests and documentation)

**Comment by otraore** [comment]
This is one of those things I had in the back of my head but never made an issue for. Thank you for bringing it up :D

**Comment by paked** [comment]
What sort of guidelines does everyone think we should have in place?

I'm thinking about:

- "git commit message" guide.
- Every PR should have godoc style comments on ever piece of code modified, regardless of whether or not it had documentation before
- If the PR breaks backwards compatibility it should be noted in the README
- Tests should be added if at all possible. PRs without tests will be merged, but a PR with tests is more favourable than one without.

**Comment by otraore** [comment]
And gofmt? @paked

**Comment by paked** [comment]
I thought that was a given already :p

**Comment by otraore** [comment]
Closed by #396
