### ISSUE TITLE
Requires GIT

### ISSUE THREAD

**Issue by christopherghenderson** [EngoEngine/engo#378]
The instructions dont say anything about installing GIT, which is not preinstalled on Ubuntu.

**Comment by otraore** [comment]
Arguable, but I think since it obviously requires go, and `go get` requires git, it is a pretty obvious dependency. I still have no problems if we explicitly state this but it is sort of obvious.

**Comment by paked** [comment]
Git isn't the only way go get works though. I think this is a pretty fair
request.

**Comment by otraore** [comment]
I agree but it's pretty rare using go-get without git. Almost every external dependency or it's dependencies require git. But still a valid request.
