### ISSUE TITLE
[Two Error] OSX Mouse ,Android don't work

### ISSUE THREAD

**Issue by nzlov** [EngoEngine/engo#379]
in osx,run pong,the mouse exist deviation.
osx 10.11.6 
macbook pro 15 retina

in android, `mouse`  demos  don't work

**Comment by nzlov** [comment]
in retina osx,must mouse x2,link
`engo_glfw.go`
```
	window.SetCursorPosCallback(func(window *glfw.Window, x, y float64) {
		Input.Mouse.X, Input.Mouse.Y = float32(x)*2, float32(y)*2
		Input.Mouse.Action = Move
	})
```

**Comment by nzlov** [comment]
In the PC using the window mode, should detect where the mouse to enter?

**Comment by EtienneBruines** [comment]
> In the PC using the window mode, should detect where the mouse to enter?

We're currently not doing anything with "mouse entered window". We're happy to receive requests, though - so I'll leave this up for grabs.

**Comment by otraore** [comment]
@paked Reopening because he also mentioned the mouse demo doesn't work on android; I don't think we've looked into that yet.
