### ISSUE TITLE
Texture positioning

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#386]
Currently, textures get drawn starting from the top-left coordinate, in the area to the bottom/right. 

When an ingame-unit with size (10, 10) is at location (100, 100), you therefore have to manually set the location to (100-10/2, 100-10/2), in order to center is correctly. 

What if we added a `Positioning` member of the `RenderComponent` struct? By default, it would be `TopLeft`, but would allow the option of `Centered`?

This would make creating games _a lot_ easier (and the code would look better). 

Thoughts, @paked @otraore ?

**Comment by paked** [comment]
SGTM

**Comment by Think-Jumper** [comment]
Same question.It's better use the bottom/left coordinate.

**Comment by lukevers** [comment]
I did something similar to this back when I was playing with engo months ago. The repository is a mess, so ignore how horrible it is, but: https://github.com/lukevers/arp147/blob/b91d66269358b89d063119ac16a592bae66fb856/src/arp147/ui/position.go

**Comment by Noofbiz** [comment]
SpaceComponent now has Center() and SetCenter() which does this. For any corner, such as bottom left, it shouldn't be too hard to write a function yourself that just sets it using that corner from the position and width or height.
