### ISSUE TITLE
Why don't systems look for entities with specific groups of components?

### ISSUE THREAD

**Issue by Reificator** [EngoEngine/engo#387]
One of the advantages I've always thought of an ECS having is that you can define a new system that works on existing components, without changing the code for those components.  (This lets you get a little closer to having entities defined purely through data, which makes an editor surprisingly trivial)

While going through [the tutorial](https://engo.io/tutorials/01-hello-world), this chunk of boilerplate immediately jumped out at me as a point of concern.

``` Go
for _, system := range world.Systems() {
    switch sys := system.(type) {
    case *common.RenderSystem:
        sys.Add(
            &city.BasicEntity,
            &city.RenderComponent,
            &city.SpaceComponent,
        )
    }
}
```

In any reasonably sized game, we're going to want to have dozens of systems affecting any particular entity, and so this switch is going to become very large very quickly.  Furthermore adding a new system will require us to update dozens of new entities, determining at each point which entities need to be affected and which should not, and leading to situations where an entity that should be affected was not included, and is therefore not being updated.  And toggling systems on and off during debugging becomes too much effort to justify.

We see this same boilerplate applied in our city building component, and in doing so we now have to jump through some (reasonably minor) hoops in order to get a pointer to the `World`.  So now our systems that should be as functional as possible (IMO, your mileage may vary) have to keep track of state.  (There's also the reference to the mouse component, but that's a different story)

The [Entitas](https://github.com/sschmid/Entitas-CSharp) ECS is just one example of an ECS that doesn't have this requirement.  Instead the systems request to be updated with entities that match a certain set of requirements, namely possessing a set of components that the system is concerned with.

``` C#
var entities = pool.GetEntities(Matcher.AllOf(Matcher.Move, Matcher.Position));
foreach (var entity in entities) {
    var move = entity.move;
    var pos = entity.position;
    entity.ReplacePosition(pos.x, pos.y + move.speed);
}
```

For example, let's say we're building a space game like Asteroids, but with no map limit.  We simply want to generate a world around the player as they travel.  Depending on our scale and our speed of travel, we will eventually reach a point where floating point errors become noticeable and start affecting gameplay.  To combat this, we can simply create an entity that keeps track of our current distance from the world origin, and position everything relative to that offset.  With this theoretical ability to filter entities by components, this becomes a single tiny system that no entities except the world generation ever need to know about.  And by storing the offset in an entity we gain the ability to query that entity when we do need it.

``` Go
func (sys *OffsetSystem) Update(dt float32) {
    // These should probably be retrieved by component type so we're less fragile/easier to mock,
    // but that's beyond the scope of this question so we'll assume we're caching them.
    offset := sys.offset
    playerSpace := sys.playerSpace

    // If we're reasonably close to the offset still, bail out early
    if offset.PointDistanceSquared(playerSpace.Position) < 1000 * 1000 {
        return
    }

    // Update the offset to place the player at origin.
    offset.Subtract(playerSpace.Position)

    // And apply that difference across all components that exist in space.
    // Imagination required here...
    entities := sys.world.GetEntitiesWithComponents(common.SpaceComponent)
    for _, entity := range entities {
        entities.SpaceComponent.Position.Add(offset)
    }
}
```

Having the ability to have a system specify what components it's interested instead of the other way around has the added benefit that we can use empty components as flags.  Instead of a large switch adding an entity's components to multiple systems, we simply add a flag component that lets us opt-in or opt-out of a given system.  By making this a part of the entity's state we can now toggle temporary effects or other metadata.

For instance in multiplayer game where players die and respawn, you can have each player controlling an entity in the world.  Each playable entity has a `PlayerControlComponent{PlayerId: x}` attached.  Triggering a player's death animation is now as simple as removing the `PlayerControlComponent` and changing the `Animation` component to point to a different animation.  Respawning the player becomes as simple as instantiating a new entity, no more duplicate logic between instantiation and resetting the player to a random spawn point, remembering to take away their items, reset their health to 0, etc.  Allowing the player to control multiple entities at the same time _may_ be as simple as attaching a `PlayerControlComponent` with that player's ID to more than one entity, depending on your control scheme.

**Comment by Reificator** [comment]
EDIT: Replaced time based early exit in `OffsetSystem.Update` example with a distance based one instead.  Less state and closer to our actual needs.

**Comment by coderconvoy** [comment]
Some objects with components will not want to be acted upon by every system that can.

Also, there are many more entities than sytems.
Having to look through them all and see which ones meet a criteria every single update (using reflection) will be just as slow, if not slower than having a check once for each object at it's creation.

**Comment by Reificator** [comment]
I didn't mean to imply that the logic can't happen at entity creation, or that there can't be a per system cache of what entities need to be processed.  Just that the client code responsible for creating the entity should not be responsible for this registration.

> Some objects with components will not want to be acted upon by every system that can.

I guess this is a fundamental difference between what I'm after and what this library provides then.  Because in my mind it's central to the idea of an ECS that having a certain set of components means that systems interested in those components will affect it.  And if you want to pick and choose entities to be affected, then you add a flag component that either includes or excludes that entity from processing.

What happens to an entity should be entirely determined by what components it contains IMO.  Debugging why an entity with a transform and a velocity is not moving should be a matter of making sure it has those components and making sure the velocity system is working as intended.

Furthermore the naive approach to game saves with an ECS is to serialize the entities if they exist as more than an ID, and their components as well.  Then deserialize to load a save.  But if each entity must register itself on creation to be updated by a system, now you've lost significant amounts of information and the game will play out differently after a load than it would have before the load.

And I bring up that approach to game saves because it's also a great way to debug strange behavior.  But if the game behaves differently before and after a save and reload, that goes out the window.

**Comment by Noofbiz** [comment]
I actually like this a lot, but nothing can actually be done about that here, the issue belongs in EngoEngine/ecs, but it'll also require major refactoring of the way common and demos work, as well as be a major breaking change.  I think I'll try it out myself and see. @paked @otraore @EtienneBruines what do you guys think? 

From what I gather, it is basically removing the entities and add/remove methods from System and adding the entities directly to the world. Then the world would update each system, and the system would look at each entity see if it can operate on it. This part might be fairly simple, actually, if we utilize the interfaces (Renderable, Mouseable, etc)

**Comment by EtienneBruines** [comment]
I think there might be some performance drawbacks into "figurinrg out which entities to work with" in the `Update` function. We may be able to propagate the `Add` function, so one can add the `Entity` to the `World`, which would automatically add it to every applicable `System`. But doing this check on `Update` will have a negative impact on the runtime performance. There shouldn't be a reason doing this in `Update` either, since an `Entity` usually won't implement interface `A` on one frame, and then `B` in the next. 

That said, only few games need to squeeze out that last bit of performance. It'd be great to allow games that need it, to keep doing it in the "performance-first" kind of manner. Going over all items linearly, single-threaded might not be the best performance-wise, so it'd be good to still allow for alternatives. (like the `System`s keeping a list of which `Entity`s they want to work with)

Going the `Interface`-route and adding `Entities` to the `World` (which adds them to `System`s), sounds pretty good.

**Comment by Noofbiz** [comment]
I've got a working attempt at this going on here https://github.com/Noofbiz/ecs/tree/noofbiz/auto-system-add. It tries for the best of both worlds, the `World` keeps a map of the systems and the entities that are in them, so it only has to iterate over all of them when a system is added. Check out the entity tests to see how the Systems would work with this implementation. Basically, systems are now an update and a filter function, which filters the entities into the ones that it acts upon.

**Comment by Noofbiz** [comment]
I've managed to do it without breaking anything :+1:  https://github.com/Noofbiz/ecs/tree/noofbiz/auto-system-add-two instead it adds an AddByInterface to systems if they want to implement this, and what it does is call that on all the entities as you add them. Uses the current method, but provides a way to do it automatically as long as they implement the interfaces and can call AddByInterface ^_^
