### ISSUE TITLE
Mouse scaling is way off on OSX (maybe Retina issue?)

### ISSUE THREAD

**Issue by duckpuppy** [EngoEngine/engo#388]
I'm working through the Traffic tutorial, and I've written the code in Tutorial 2.  On OSX, the mouse positioning seems to be WAY off.  In the attached screenshot, I pressed "F1" with the mouse cursor 
on each corner of the game window.  The placed cities show how far off those clicks were. I think this is the same thing that the first bit of #379 is talking about.

> in osx,run pong,the mouse exist deviation.
> osx 10.11.6 
> macbook pro 15 retina

<img width="405" alt="screen shot 2016-09-23 at 4 57 25 pm" src="https://cloud.githubusercontent.com/assets/19253/18801138/06fa5996-81af-11e6-9b12-8323991f9e87.png">

**Comment by EtienneBruines** [comment]
We currently have (for a few months now) code in place that should "fix" this, but no-one in our team has a retina display to play around with. 

If I happen to be at the [gitter chat](https://gitter.im/EngoEngine/engo) around the same time as you are, I'd be happy to debug this (but I'd need your help, since you're the one that can test whether or not it works).

**Comment by MadWombat** [comment]
I am having the same problem. Thank you for the code pointers. I will see if I can find out what is going on. I will report any results here.

**Comment by MadWombat** [comment]
Before I get any further, I would like to point out that apparently the program is not limited by the window size/scale. I have just tried the following.
1. Follow the tutorial through part 2
2. Run the program
3. Press F1 with mouse pointer in every corner of the screen
4. Press F1 with mouse pointer in every corner of the program window

This is the result
<img width="512" alt="screen shot 2016-12-15 at 4 32 35 pm" src="https://cloud.githubusercontent.com/assets/242806/21242853/452f9066-c2e4-11e6-8e8f-33db1bd8b708.png">

**Comment by MadWombat** [comment]
And this is what I get when I log window and viewport dimensions in the CreateWindow() function
```
2016/12/15 16:35:54 Using standard inputs
2016/12/15 16:35:55 Window Height:  400
2016/12/15 16:35:55 Window Width:  400
2016/12/15 16:35:55 Viewport Height:  800
2016/12/15 16:35:55 Viewport Width:  800
2016/12/15 16:35:55 Scale:  2
CityBuildingSystem was added to the Scene
```

**Comment by MadWombat** [comment]
I have tried adding logging to CursorPos(), but didn't get any results. The tutorial uses MouseTracker component to figure out the coordinates though, so CursorPos() is never called. Instead mouseTracker.MouseComponent.MouseX and mouseTracker.MouseComponent.MouseY properties are used to determine where to place the new icon.

A casual code search lead me to believe that these properties are set in Update() function in engo.io/engo/common/mouse.go and I do not see scale used anywhere in there. That might be the problem.

**Comment by MadWombat** [comment]
Before I go offline, I found another weird thing. I have tried multiplying MouseX and MouseY by scale in window.SetCursorPosCallback and window.SetMouseButtonCallback. When I positioned the cursor in the corner of the game window and press F1, I would get numbers close to 0 in the log, which is expected, but the resulting city icon still ends up some way down and right in the window. It seems that there is more than one problem here and for some reason 0,0 coordinates do not map to the left top corner of the game window.

**Comment by MadWombat** [comment]
More information. I have reverted the tutorial back to step one, where you just draw icon entities on the window, scaled the city entity to 0.1, so it doesn't take the whole screen and placed two entities at 0,0 and 400,400. Here is the result:
<img width="512" alt="screen shot 2016-12-16 at 1 09 54 pm" src="https://cloud.githubusercontent.com/assets/242806/21273313/f6a54668-c390-11e6-8be5-40645792d7c8.png">

**Comment by MadWombat** [comment]
Found an interesting comment in the GLFW docs
```
Do not pass the window size to glViewport or other pixel-based OpenGL calls. The window size is in screen coordinates, not pixels. Use the framebuffer size, which is in pixels, for pixel-based calls.
```

**Comment by MadWombat** [comment]
I have looked into this issue more, but unfortunately I do not know anything about OpenGL programming and I quickly got lost. Not sure I can investigate any further.

**Comment by MadWombat** [comment]
Any word on this? I can help with testing, but I don't know enough about OpenGL to actually fix this.

**Comment by otraore** [comment]
> And this is what I get when I log window and viewport dimensions in the CreateWindow() function
> 
> 2016/12/15 16:35:54 Using standard inputs
> 2016/12/15 16:35:55 Window Height:  400
> 2016/12/15 16:35:55 Window Width:  400
> 2016/12/15 16:35:55 Viewport Height:  800
> 2016/12/15 16:35:55 Viewport Width:  800
> 2016/12/15 16:35:55 Scale:  2
> CityBuildingSystem was added to the Scene

@MadWombat what did you log to the get viewport height and width? Did you log the `w` and `h` variables from this [line](https://github.com/EngoEngine/engo/blob/d04ef0b08f11203140127680939513790f3d50f8/engo_glfw.go#L115)?

**Comment by MadWombat** [comment]
No, the SetFramebufferSizeCallback() never gets called for me. I logged canvasWidth and canvasHeight from [this line](https://github.com/EngoEngine/engo/blob/d04ef0b08f11203140127680939513790f3d50f8/engo_glfw.go#L109)

**Comment by MadWombat** [comment]
I just found a weird effect. If I log scale variable value, it gets set to 2 at the app start, but if I resize the window it gets reset back to 1. The coordinates problem just gets worse though.
