### ISSUE TITLE
File.Load(url) broken

### ISSUE THREAD

**Issue by Arkessler** [EngoEngine/engo#389]
I've been trying to do the tutorial and have been encountering issues with engo.Files.load being unable to open any resources. I decided to copy over and test the falling demo, but encountered the same issue. Here is what I got when trying to run falling.exe

$ ./falling.exe
2016/10/15 08:55:18 Using standard inputs
2016/10/15 08:55:18 unable to open resource: open assets\icon.png: The system cannot find the path specified.
2016/10/15 08:55:18 resource not loaded by `FileLoader`: "icon.png"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x401a7a]

This is with the assets in the assets folder

~/Documents/Programming/Go/src/github.com/Arkessler/falling/assets
$ ls
icon.png  rock.png

**Comment by EtienneBruines** [comment]
What's your working dir when executing `falling.exe`? Does the problem also occur when running `go run falling..go`?

**Comment by Arkessler** [comment]
My working dir for executing the exe was $GOPATH/bin. When I try to run the file by using go run in the src directory I get the following.

Alexi Kessler@AlexiKessler-PC MINGW64 ~/Documents/Programming/Go/src/engo.io/engo/demos/falling (master)
$ ls
assets/  falling.go  README.md

Alexi Kessler@AlexiKessler-PC MINGW64 ~/Documents/Programming/Go/src/engo.io/engo/demos/falling (master)
$ go run falling.go
falling.go:8:2: cannot find package "engo.io/ecs" in any of:
        C:\Go\src\engo.io\ecs (from $GOROOT)
        C:\Users\Alexi\ Kessler\Documents\Programming\Go\src\engo.io\ecs (from $GOPATH)
falling.go:9:2: cannot find package "engo.io/engo" in any of:
        C:\Go\src\engo.io\engo (from $GOROOT)
        C:\Users\Alexi\ Kessler\Documents\Programming\Go\src\engo.io\engo (from $GOPATH)
falling.go:10:2: cannot find package "engo.io/engo/common" in any of:
        C:\Go\src\engo.io\engo\common (from $GOROOT)

**Comment by otraore** [comment]
@Arkessler Run `go get -u` from the working dir and then try running `go run falling.go`. It seems like you didn't install the dependencies for engo.

**Comment by EtienneBruines** [comment]
The demos were intended to run from directories like `src/engo.io/engo/demos/falling ` as the working directory. 

Doing as @otraore said, should help.

**Comment by otraore** [comment]
Any updates on this @Arkessler ?

**Comment by otraore** [comment]
@Arkessler any updates? I'd like to get this issue fixed or closed depending on if our suggestion worked for you.

**Comment by otraore** [comment]
@Arkessler since you haven't been active both on this issue and on github and we think this was a simple issue that our suggestion likely fixed, I'm going to close this issue. You're welcome to reply if it didn't work for you and I will gladly reopen it then. Thank you.
