### ISSUE TITLE
Impossible to scroll on subsequent scenes

### ISSUE THREAD

**Issue by johnny-morrice** [EngoEngine/engo#392]
It's impossible to do CameraSystem based scrolling on all but the first scene.  (I have tested with EdgeScroller but I believe this applies across the board)

Why?

On shader initialization, the global shader instances (e.g. DefaultShader) grab a reference to the first CameraSystem they find (See *DefaultShader Setup method).

When the user creates a new RenderSystem for use in a second scene ([as per the examples](https://github.com/EngoEngine/engo/blob/master/demos/scenes/scenes.go)), a new CameraSystem is created, but the references in the shaders are not updated.

Here is a quick and stupid fix whereby a single CameraSystem instance persists across all RenderSystem instances:

```
func (rs *RenderSystem) New(w *ecs.World) {
	rs.world = w

	if __camera == nil {
		__camera = &CameraSystem{}
	}

	w.AddSystem(__camera)

	if !engo.Headless() {
		initShaders(w)
		engo.Gl.Enable(engo.Gl.MULTISAMPLE)
	}

	engo.Mailbox.Listen("renderChangeMessage", func(engo.Message) {
		rs.sortingNeeded = true
	})
}

var __camera *CameraSystem
```

This is stupid but you'll find that one can now scroll in scenes after the first.

Another suggestion is that one could fix the bug by ensuring the CameraSystem instances are not shared across global variables such as DefaultShader.  Perhaps by turning those global variables into instance variables or methods.  As I'm not a core contributor I don't know what design you have in mind.

**Comment by countcb** [comment]
Added a PR with an idea to fix this here: https://github.com/EngoEngine/engo/pull/420
