### ISSUE TITLE
Assets embedded in the binary

### ISSUE THREAD

**Issue by clebs** [EngoEngine/engo#400]
Hi,

I have been thinking it would be a great feature to be able to embed resources into the final binary by integrating [go-bindata](https://github.com/jteeuwen/go-bindata) That way everything that has to be shipped together with the program for it to work is always there (e.g. Sprites, sounds,...).

**Proposal:**

`Files` would have 2 separate handlers:
- Internal: manages files embedded in the program via go-bindata (read only).
- external: manages files in the file system as it does right now (read and write).

What do you think about it?

Cheers.

**Comment by otraore** [comment]
The idea has actually crossed my mind before but I hadn't thought of a plausible implementation. I didn't want to complicate using it but I wanted to make it optional. I think it's a good idea if done right.

**Comment by clebs** [comment]
I agree that it has to be optional yes, which is why I suggested the internal and external file scopes.
It should not mandatory to use embedded files.

Engo would only provide integration for go-bindata embedding so we can use `Files` instead of adding custom code to use go-bindata each time.

**Comment by thecarp** [comment]
I have been thinking of this from another angle. TMX tilesets already can exist as either independent files or emeded within a tmx file. You could have a situation where multiple maps refer to the same tileset asset; or it may even be convinent to make a reference to a tileset that exists internally within another tmx file.

I propose a scheme, to explicitly mimic urls elsewhere. Allow a '#' suffix on a url which denotes information contained within another url. The main blocker to doing this is that file loading relies exclusively on file suffix to find loaders. (see #324 )

If this was not the case we could define a file loader for a binary type like .tar.gz or .zip, then have the loader chain load each of the files within it. Producing something like "example.zip#map.tmx" or even "example.zip#map.tmx#set1.tst"

**Comment by clebs** [comment]
I am not sure if we are talking about the same, correct me if I am wrong.
How would we represent an embedded file in our binary with this notation?
Having a reserved word it would look for such as `#internal#myAsset.ext` looks too fragile too me.

I was suggesting having `Files` provide access to 2 interfaces (internal, external) which would locate files differently.

**Comment by thecarp** [comment]
Actually I have convinced myself we are talking about the same thing, but I had to do a bit more thinking on it. Basically, anything that will let you insert your embeded data as assets, will let me insert mine too. Also, this has become a blocker for some of the refactoring work I am doing.

I have most of a proposal prepared here [400-assets-internal](https://github.com/EngoEngine/engo/compare/master...thecarp:400-assets-internal)

The tldr is a new interface DataLoader which requires an Insert(url, interface{}) error 

This is implemented as an optional interface to a FileLoader. 

A new companion function to engo.Files.Load() engo.Files.Insert() uses the file name to locate the loader as normal, then checks to see if it implements the FileLoader interface, and generates an error if not. If it does, then it passes the url and data on to its Insert receiver.

Insert functions are mostly thin copies of Load functions.

I implemented only one example of DataLoader and the test function attempts to use it to load a png file as an image.Image. This seems to be close to working, but generates a runtime error down in texture creation. I am a little baffled as to why, but I am a bit of a novice with interface casting.

**Comment by Asday** [comment]
Correct me if I'm wrong, but say I made a giant game in such an engine, on the scale of BluRay distribution, wouldn't the binary not be able to load as it wouldn't fit into memory?

**Comment by thecarp** [comment]
You are not wrong, but if you have a BlueRay distribution medium, you already have a solution to how you keep the files together. This is going to be most useful for either games without much data, demos, unit tests, and chain loading data inside other structures.

My use case is the perfect example, a tmx map contains references to external images, but it can also contain image data. I want to normalize all of these into just image assets and support both seamlessly.

I also want to add unit tests as I work, and this will be great for mocking up data for tests.

**Comment by Asday** [comment]
Aah I see, so this wouldn't be a new direction for engo, just a possibility; "hey you can bundle your assets if they're small"?

Apologies; I haven't had time to read the code.

**Comment by Noofbiz** [comment]
Added LoadReaderData(url, io.Reader) that can read data from a file that you've elsewhere obtained the io.Reader for, such as go-bindata.
