### ISSUE TITLE
Can we Use interfaces for system.Add

### ISSUE THREAD

**Issue by coderconvoy** [EngoEngine/engo#401]
So, whenever we want to add an object to a system, we have to use a functioncall like this

`someSystem.Add(&ob.BasicEntity, &ob.OtherComponent, &ob.SomeOtherNeededComponent)`

I think there is a better way that happens to also be typesafe.

What if we give the components a getSelf type method, 

`func (be *BasicEntity) GetBasicEntity() *BasicEntity{
    return be
}`

This way, every object with a BasicEntity component, will have the method getBasicEntity()

Now we can define an interface like

`type Basic-space-ren interface{
    getBasicEntity() *BasicEntity
    getSpaceComponent() *SpaceComponent
    getRenderComponent() *RenderComponent
}`

our system.Add method can now recieve the interface, though for backward compatability, I would suggest "AddByInterface"

`func (rs *RenderSystem) AddInterface(ob basic-space-ren){
    rs.Add(ob.GetBasicEntity(),ob.GetRenderComponent(),ob.getSpaceComponent())
}`

Finally at the user end, adding is simple and typechecked. 

`sys.AddByInterface(object)`

This is scalable, as we only need to add one method for each component and one method for each system.

It is also using Go interfaces how they love to be used, as every object with the components automatically completes the interface.

I'm happy to go through and do it if you will let me.

**Comment by otraore** [comment]
I think this is a great idea. I'm in the process of building a small [game](https://github.com/otraore/space-shooter) with engo (mainly with the goal of building a reusable gui library) but adding to systems can become a pain. I would only suggest some naming changes. First removing `Get` before the start of the functions as per [effective go](https://golang.org/doc/effective_go.html#Getters).

**Comment by otraore** [comment]
Closed by #414.

Thank you on behalf of the Engo Maintainers. We really appreciate it.
