### ISSUE TITLE
Pong Demo crashes on Windows

### ISSUE THREAD

**Issue by failattu** [EngoEngine/engo#405]
Hello,

So I have managed to install engo with 
go version go1.7 windows/amd64
windows 7
Cygwin  with gcc in path 

$ gcc --version
gcc.exe (GCC) 4.8.3
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling engo is okay and packages seem to arrive correctly I get the following error:

2017/01/21 15:41:59 unable to open resource: open assets\Roboto-Regular.ttf: The system cannot find the path specified.
2017/01/21 15:41:59 Could not load font: resource not loaded by `FileLoader`: "Roboto-Regular.ttf"
2017/01/21 15:41:59 Could not load texture: resource not loaded by `FileLoader`: "ball.png"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x401b91]

goroutine 1 [running, locked to thread]:
panic(0x5f91c0, 0xc04200e0e0)
        /go/src/runtime/panic.go:500 +0x1af
main.(*PongGame).Setup(0x759498, 0xc04200a8a0)
        /src/engo.io/engo/demos/pong/pong.go:76 +0x561
engo.io/engo.SetScene(0x712f60, 0x759498, 0x472a00)
        /src/engo.io/engo/scene.go:98 +0x207
engo.io/engo.RunPreparation(0x712f60, 0x759498)
        /src/engo.io/engo/engo_glfw.go:235 +0x5b
engo.io/engo.runLoop(0x712f60, 0x759498, 0x300)
        /src/engo.io/engo/engo_glfw.go:247 +0x16e
engo.io/engo.Run(0x0, 0x628b0b, 0x9, 0x0, 0x320, 0x320, 0x100, 0x3c, 0x0, 0x1, ...)
        /src/engo.io/engo/engo.go:148 +0x422
main.main()
        /src/engo.io/engo/demos/pong/pong.go:470 +0xd3

Files can be found under the folder: LICENSE.txt  Roboto-Regular.ttf  ball.png  paddle.png

Something windows specific maybe?

**Comment by failattu** [comment]
hello-world also crashes:

2017/01/21 15:52:23 resource not loaded by `FileLoader`: "icon.png"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x4017c5]


so maybe something with the file loader.. will look into this bit more.

**Comment by EtienneBruines** [comment]
What is your working directory?

We assume this is `$GOPATH/src/engo.io/engo/demos/pong`.

**Comment by failattu** [comment]
Yup exactly like that.

**Comment by otraore** [comment]
That's because engo doesn't current embed the resources into the executable. Since you installed pong and didn't run it within it's own directory it can't find the resources. Embedding assets into the binary is being discussed [here](https://github.com/EngoEngine/engo/issues/400).

**Comment by failattu** [comment]
That explains it. #400  solves this.

**Comment by failattu** [comment]
Solution move the binary to the pong folder or compile it there. 

Thanks solves this.

**Comment by otraore** [comment]
No problem.
