### ISSUE TITLE
Circle BorderColor not working correctly

### ISSUE THREAD

**Issue by countcb** [EngoEngine/engo#407]
When drawing a circle with a border the border color is not drawn correclty.

Setting the same color for the fill and the border with this code:

	circle1 := MyShape{BasicEntity: ecs.NewBasic()}
	circle1.SpaceComponent = common.SpaceComponent{Position: engo.Point{200, 200}, Width: 200, Height: 200}
	circle1.RenderComponent = common.RenderComponent{Drawable: common.Circle{BorderWidth: 10, BorderColor: color.RGBA{255, 255, 100, 255}}, Color: color.RGBA{255, 255, 100, 255}}

	circle2 := MyShape{BasicEntity: ecs.NewBasic()}
	circle2.SpaceComponent = common.SpaceComponent{Position: engo.Point{200, 500}, Width: 200, Height: 200}
	circle2.RenderComponent = common.RenderComponent{Drawable: common.Circle{BorderWidth: 10, BorderColor: color.RGBA{1, 255, 0, 255}}, Color: color.RGBA{1, 255, 0, 255}}

	rectangle1 := MyShape{BasicEntity: ecs.NewBasic()}
	rectangle1.SpaceComponent = common.SpaceComponent{Position: engo.Point{500, 200}, Width: 200, Height: 200}
    rectangle1.RenderComponent = common.RenderComponent{Drawable: common.Rectangle{BorderWidth: 10, BorderColor: color.RGBA{255, 255, 100, 255}}, Color: color.RGBA{255, 255, 100, 255}}

	rectangle2 := MyShape{BasicEntity: ecs.NewBasic()}
	rectangle2.SpaceComponent = common.SpaceComponent{Position: engo.Point{500, 500}, Width: 200, Height: 200}
	rectangle2.RenderComponent = common.RenderComponent{Drawable: common.Rectangle{BorderWidth: 10, BorderColor: color.RGBA{1, 255, 0, 255}}, Color: color.RGBA{1, 255, 0, 255}}

produces this image:

![image](https://cloud.githubusercontent.com/assets/3466449/23275175/c01c151c-fa05-11e6-907f-1a1aeadcd5a3.png)

It seems that as soon as r, g b or a are set to something >0 it is interpreted as 255.

Rectangles don't have this issue.
I have not tried with different shapes.

**Comment by countcb** [comment]
Submitted a pull request for this
https://github.com/EngoEngine/engo/pull/411

**Comment by otraore** [comment]
Fixed in: https://github.com/EngoEngine/engo/pull/411
