### ISSUE TITLE
Fix travis builds

### ISSUE THREAD

**Issue by otraore** [EngoEngine/engo#415]
At first the I updated go to 1.8 because [gopherjs requires it](https://travis-ci.org/EngoEngine/engo/builds/204959932#L404). Now there's a gomobile and mgl32 issue [here](https://travis-ci.org/EngoEngine/engo/builds/204856047#L616).

**Comment by coderconvoy** [comment]
Have you tried running go generate in mgl32, as the code is generated from mgl64.

**Comment by otraore** [comment]
I have not @coderconvoy, I'll give it a shot soon

**Comment by otraore** [comment]
Partially fixed in #409 . Gomobile isn't building on Go 1.8 on travis (builds locally) but Gopherjs requires latest go version (1.8). In the meantime, so it doesn't block other issues, gopherjs testing is removed. I will leave the issue open since it's still relevant to fix it properly.

**Comment by Noofbiz** [comment]
Mostly fixed. Everything builds and the normal tests all pass, but I want to make sure that the gopherjs tests are in working order before closing this

**Comment by Noofbiz** [comment]
Fixed in #551
