### ISSUE TITLE
How can you get the coordinates of the top left corner of screen? [Help Wanted]

### ISSUE THREAD

**Issue by AnkithD** [EngoEngine/engo#416]
I would like to know the in-world x and y position of the top left of the screen. What is the best way to go about this?

Edit: Question Answered by @countcb . Not sure how to close this issue

**Comment by countcb** [comment]
Hi, I also answered on Gitter.

Here a copy what I wrote there:
"@AnkithD If you use the CameraSystem to move your view around you can probably get the coordinates from the CameraSystem with the X() and Y() methods."
