### ISSUE TITLE
Isometric Tilemap Support

### ISSUE THREAD

**Issue by thecarp** [EngoEngine/engo#418]
Basic isometric support with a new isoadventure demo can be found on my [isometric branch](https://github.com/thecarp/engo/tree/isometric)

Most of my testing has been with the staggered isometric, which was the most difficult to get coordinate mapping to work properly. 

Included test assets are pretty ugly, my first attempt at isometric tiles in blender. 

It would be nice to support exposing tmx properties for layers/tiles so that walkability testing can be implemented but, that will need some more code cleanup and thought.

**Comment by thecarp** [comment]
I wanted to give a bit of an update on this. I am leaving this branch as an example for myself and stepped back to do some refactoring of the tilemap code. 

I am not really satisfied with the mess trying to use zIndex to allow an outside object to sort into the map, and I think it makes more sense to create ECS components for the map so that an object can have a map component that maps it into the map space.

The above reference isometric branch is non-breaking, and so is my current work.

I expect this will result in breaking changes, but, that should remove the need for tilemap consumer code to iterate the tiles adding SpaceComponents to each.

**Comment by Noofbiz** [comment]
Hello @thecarp, would you mind if I used your branch to incorporate this into the current tilemap loading?
