### ISSUE TITLE
Can world.RemoveEntity and system.Remove recieve an interface (no backwards)

### ISSUE THREAD

**Issue by coderconvoy** [EngoEngine/engo#419]
I really feel that the system Remove method should recieve an interface

```
type IDer interface{
   ID() uint64
}

func (s *__System) Remove(e IDer){
   id = e.ID()
   for i,item := range s.entities{
        if id == item.ID() {
            //remove code
        }
    }
    //remove code
}
```

I know this breaks backward compatability, but receiving interfaces is a good thing to do, and All Entities naturally have the ID method so it's slightly simpler both inside and outside of the package.

The Remove calls people have made will still work, but users Remove methods will need updating

**Comment by AnkithD** [comment]
What would be the advantage? Won't every entity have a BasicComponent which implements ID() any way?

**Comment by coderconvoy** [comment]
No major actual advantage.

instead of typing s.Remove(ob.BasicEntity)
you now type s.Remove(ob)

It feels a bit better to me is all

**Comment by coderconvoy** [comment]
this would be more handy with systems that store interfaces instead of creating new entities, (all the ones I make, as in those, I have to type.

s.Remove(*ob.GetBasicEntity())

**Comment by Noofbiz** [comment]
I'm going to close this here, as it would have to be fixed on EngoEngine/ecs rather than engo
