### ISSUE TITLE
engoengine/math.Sqrt / Sin / etc do not work with gopherjs

### ISSUE THREAD

**Issue by countcb** [EngoEngine/engo#421]
This can be reproduced with the mouse demo.

Problem is:
collision.go triangleArea calls 
engo.Point.PointDistance
in which engoengine/math.Sqrt is used.

Uncaught Error: runtime error: native function not implemented: github.com/engoengine/math.Sqrt

All functions without a body are leading to this problem.

Am I doing something wrong?

Edit: I'm using version: GopherJS 1.8-1

**Comment by otraore** [comment]
I believe it's because the math library uses assembly code which isn't runnable on gopherjs for obvious reasons. 

Ex: [here](https://github.com/EngoEngine/math/blob/master/sqrt_amd64.s) and [here](https://github.com/EngoEngine/math/blob/master/sqrt_386.s)

I believe this could be fixed if we used javascript compatible versions for gohperjs (written in pure go).

**Comment by countcb** [comment]
Wouldn't the standard go math package be OK for this? Or what is the reason you use a special math package?

I'm on phone only currently so I can't check. So if there are obvious reasons excuse me :)

**Comment by countcb** [comment]
Would the approach be to make a pure go version only for JavaScript?
Or use a pure go version everywhere?

No matter what approach I could have a look at this next week (will be gone till Tuesday).

Without having put much thought into it, I currently would make a special version only for JavaScript and the simplest approach would be to just write a wrapper around the standard math lib and cast everything to float32.
It could be changed for performance reasons but my first approach would have the goal to make it compatible again with gopherjs.

**Comment by otraore** [comment]
That sounds good @countcb, If I'm free by next tuesday I could take a go™ at it.

**Comment by countcb** [comment]
Pushed my idea here https://github.com/EngoEngine/engo/pull/426

**Comment by otraore** [comment]
Fixed in: https://github.com/EngoEngine/engo/pull/426
