### ISSUE TITLE
Redefine engo.Mailbox methods to take pointers as arguments

### ISSUE THREAD

**Issue by AnkithD** [EngoEngine/engo#425]
Sometimes it might be necessary for one system to get some data from another. Since dispatch and listen functions do not return anything this will be challenging. Also i don't think it would be a good idea to make it return an interface either(?)

If we did make the message a pointer, then modifying the message in the listen methods handler will be seen by the system that dispatched the message. So in the message struct itself we can have some fields that are left empty in order for them to be filled out by the Listening system.

example:

	// In Dispatching System
	type ResourceRequest struct {
		ResourceType string

		ResourceVal  int
	}

	mymsg := ResourceRequest{ResourceType: "TypeA"}
	engo.Mailbox.Dispatch(&mymsg)
	res := mymsg.ResourceVal
	
	//In Listening System
	engo.Mailbox.Listen("ResourceRequest", func(_msg *engo.Message) {
			msg, ok := _msg.(ResourceRequest)
			if !ok {
				panic("Wrong Message Type!")
			}

			switch ResourceType:
			case "TypeA": 
				msg.ResourceVal = thisys.getTypeA()
			case "TypeB": 
				msg.ResourceVal = thissys.getTypeB()
		})

**Comment by otraore** [comment]
You can change the values with the current system. The following outputs 1 as expected. We can't make `engo.Message` a pointer when you `Dispatch` though because go doesn't allow pointers to interfaces. But if you pass a pointer to dispatch, you can type cast it to a pointer in your Listen method so you can modify the original object. I believe this addresses your issue so I'm going to close it, if you feel it doesn't you're welcome to re-open it. Sorry for the late reply. 

```go
package main

import (
	"fmt"

	"engo.io/engo"
)

type ResourceRequest struct {
	ResourceType string
	ResourceVal int
}

func (ResourceRequest) Type() string {
	return "ResourceRequest"
}

func main() {
	//In Listening System
	engo.Mailbox = &engo.MessageManager{}
	engo.Mailbox.Listen("ResourceRequest", func(_msg engo.Message) {
		msg, ok := _msg.(*ResourceRequest)
		if !ok {
			panic("Wrong Message Type!")
		}

		switch typ := msg.ResourceType; {
		case typ == "TypeA":
			msg.ResourceVal = 1
		case typ == "TypeB":
			msg.ResourceVal = 2
		}
	})

	mymsg := ResourceRequest{ResourceType: "TypeA"}
	engo.Mailbox.Dispatch(&mymsg)
	res := mymsg.ResourceVal
	fmt.Println(res)

}

```
