### ISSUE TITLE
Circles are drawn as rectangles when using gopherjs

### ISSUE THREAD

**Issue by countcb** [EngoEngine/engo#427]
Can be reproduced with the shapes demo and gopherjs.

Run gopherjs serve and navigate to http://localhost:8080/engo.io/engo/demos/shapes/

![bildschirmfoto vom 2017-03-07 16 48 25](https://cloud.githubusercontent.com/assets/3466449/23664523/1599945c-0356-11e7-8419-ed387d0d75d0.png)

**Comment by otraore** [comment]
I have a feeling it might be related to: https://github.com/EngoEngine/engo/issues/421

**Comment by countcb** [comment]
I tried this with the changes I provided in PR 426.
So unless there is another issue I don't think that 421 has something to do with this?

**Comment by hajimehoshi** [comment]
Sometimes js build cache doesn't work well. How about removing $GOPATH/pkg/*_js once?

**Comment by Noofbiz** [comment]
Alright, I'm going to do the circles via buffer rather than in the shader, which is how it is now. http://slabode.exofire.net/circle_draw.shtml
