### ISSUE TITLE
AudioSystem - Weird sound at start

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#43]
Whenever the background music starts, I hear some kind of weird 'popping' sound. Not sure what it is, or how to fix it. Sounds almost like the speakers turning on. 

Anyone else hear that sometimes?

**Comment by EtienneBruines** [comment]
Can either of you confirm (or refute), @paked @matiwinnetou  ?

**Comment by paked** [comment]
@EtienneBruines I hear it too.

**Comment by EtienneBruines** [comment]
Up for grabs.

**Comment by matiwinnetou** [comment]
on Mac Osx - El Capital I hear this too.

**Comment by otraore** [comment]
This also might be a godoc.org/github.com/google/mobile issue.

**Comment by mewmew** [comment]
I can confirm this issue. Hear it too.

**Comment by Noofbiz** [comment]
Closed in #494
