### ISSUE TITLE
Is the Audio system supported on Android or not?

### ISSUE THREAD

**Issue by LukasMa** [EngoEngine/engo#430]
Hi,
engo.io forwarded me to Issue #174 which states that the Audio system is supported on Android:
> Currently, the AudioSystem is only available on Linux/Android/OSX. This should be addressed.

But the table in the  README says it is only supported on Linux and OSX.

So is it supported, or not?

**Comment by otraore** [comment]
Sorry for the confusion, Audio System is not currently supported on Android. I'm going to close this issue in favor of continuing AudioSystem discussion [here](https://github.com/EngoEngine/engo/issues/272). You may reopen it at any time if you feel it needs to. Thank you for checking out Engo :D.
