### ISSUE TITLE
Cannot load JPG image

### ISSUE THREAD

**Issue by GodKra** [EngoEngine/engo#431]
when i try to load a jpg image, i get the error below. PNG images work fine.

    2017/03/15 14:37:57 image: unknown format
    2017/03/15 14:37:58 resource not loaded by `FileLoader`: "enemy.jpg"
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x8 pc=0x402357]

    goroutine 1 [running, locked to thread]:
    panic(0x5f8340, 0xc04200c0b0)
        C:/Go/src/runtime/panic.go:500 +0x1af
    main.NewEnemy(0xc0420425a0, 0xc200000042a2b895)
        E:/Programming/GO/src/engoGame/game.go:122 +0x197
    main.(*EnemySpawnSystem).Update(0xc04203a178, 0x3c899ab3)
        E:/Programming/GO/src/engoGame/game.go:106 +0x76
    engo.io/ecs.(*World).Update(0xc0420425a0, 0x3c899ab3)
        E:/Programming/GO/src/engo.io/ecs/world.go:32 +0x67
    engo.io/engo.RunIteration()
        E:/Programming/GO/src/engo.io/engo/engo_glfw.go:216 +0x7d
    engo.io/engo.runLoop(0x70ff60, 0x758520, 0x400)
        E:/Programming/GO/src/engo.io/engo/engo_glfw.go:259 +0x232
    engo.io/engo.Run(0x0, 0x628507, 0xc, 0x0, 0x400, 0x280, 0x0, 0x3c, 0x100, 0x1, ...)
        E:/Programming/GO/src/engo.io/engo/engo.go:148 +0x422
    main.main()
        E:/Programming/GO/src/engoGame/game.go:198 +0xd3
    exit status 2

**Comment by otraore** [comment]
Thank you for your contribution!

I think I fixed it in https://github.com/EngoEngine/engo/pull/432. You may test it out before I can merge it in.

**Comment by otraore** [comment]
Because of inactivity and since I've personally tested it, I'm going to merge #432. If this issue still occurs you can re-open it. Thanks for bringing this to our attention.
