### ISSUE TITLE
Dynamic Preloading of Images

### ISSUE THREAD

**Issue by jamesevans** [EngoEngine/engo#434]
This is more of a hypothetical issue: I'm going through demo code / trying to use images, and I anticipate needing to "preload" a lot of assets. As I understand it, I'll have to preload every asset I could possibly want on a scene. Is there a way to dynamically "preload" those assets, so I don't need to preload my entire asset library each time?

**Comment by otraore** [comment]
The `Preload` method is just called on the creation of a scene. So it's common practice to Load all of your files there like shown [here](https://github.com/EngoEngine/engo/blob/master/demos/hello-world/hello.go#L22). You are by no means obligated to load your files there. You can just call `	engo.Files.Load("file.png")` anywhere. Just make sure you do so before trying to access the asset you need.

**Comment by otraore** [comment]
I'm going to assume this addressed your issue so I'll close it. If you feel like it didn't you're more than welcome to re-open it. Thanks for using engo.
