### ISSUE TITLE
Following the tutorial and having problems with installation

### ISSUE THREAD

**Issue by wgottschalk** [EngoEngine/engo#437]
My version of go:
`go version go1.8.1 darwin/amd64`
When working through the tutorial, I try

```
import "engo.io/engo/common
func (*myScene) Setup(world *ecs.World) {
	world.AddSystem(&common.RenderSystem{})
}
```

and I get the following error:
```
../go/src/engo.io/engo/common/camera.go:11:2: cannot find package "github.com/go-gl/mathgl/mgl32" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/go-gl/mathgl/mgl32 (from $GOROOT)
	/Users/.../go/src/github.com/go-gl/mathgl/mgl32 (from $GOPATH)
../go/src/engo.io/engo/common/font.go:13:2: cannot find package "github.com/golang/freetype" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/golang/freetype (from $GOROOT)
	/Users/.../go/src/github.com/golang/freetype (from $GOPATH)
../go/src/engo.io/engo/common/font.go:14:2: cannot find package "github.com/golang/freetype/truetype" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/golang/freetype/truetype (from $GOROOT)
	/Users/.../go/src/github.com/golang/freetype/truetype (from $GOPATH)
../go/src/engo.io/engo/common/font.go:15:2: cannot find package "golang.org/x/image/font" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/golang.org/x/image/font (from $GOROOT)
	/Users/.../go/src/golang.org/x/image/font (from $GOPATH)
../go/src/engo.io/engo/common/font.go:16:2: cannot find package "golang.org/x/image/math/fixed" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/golang.org/x/image/math/fixed (from $GOROOT)
	/Users/.../go/src/golang.org/x/image/math/fixed (from $GOPATH)
../go/src/engo.io/engo/common/audio.go:11:2: cannot find package "golang.org/x/mobile/exp/audio/al" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/golang.org/x/mobile/exp/audio/al (from $GOROOT)
	/Users/.../go/src/golang.org/x/mobile/exp/audio/al (from $GOPATH)
```

All I did was a `go get -u engo.io/engo`. It looks like dependencies are not being installed correctly but I'm new to the Go ecosystem so I'm not sure how to decipher the message

**Comment by otraore** [comment]
Hey, thanks for using engo. So first make sure you're in the directory for the project you're working on (where you're running `go run`) and just run `go get`. That should get all the dependencies. I also recommend running `go install engo.io/engo` afterward since it'll speed up future builds.

**Comment by wgottschalk** [comment]
Ok. This is resolved now. I didn't realized that Go module system is based on a global imports and advocates for a single workspace.

For future me, make sure to create a folder in `$GOPATH/src/github.com/engoengine/trafficmanager` and do all work from there. Also, if you're importing local packages, the have to be globally imported. So instead of `import ./systems` I need to import `github.com/engoengine/trafficmanager/systems` and the $GOPATH will allow Go to resolve the rest.

**Comment by otraore** [comment]
Glad it works for you, I hope you enjoy working with engo.
