### ISSUE TITLE
Godef broken for engo package, can't get contextual info/hover info

### ISSUE THREAD

**Issue by bcokert** [EngoEngine/engo#443]
Godef, which prints usage information and is also commonly used by IDE's for contextual/hover info, is broken for the engo package (eg: engo.Files.Load).

Digging in I found that it was failing due to some missing dependencies that godef couldn't follow. Running godef manually on the specific line told me exactly which packages.

I managed to fix it myself by manually installing these packages:
* ```go get -u github.com/gopherjs/gopherjs```
* ```go get -u honnef.co/go/js/dom```
* ```go get -u honnef.co/go/js/xhr```

A possible fix is to add these to the README, but I haven't created a PR yet in case you are already familiar with the problem and have a better solution in mind.

A few observations:
* ```go get -u engo.io/engo``` fails to download these itself. ```go get -u engo.io/engo/...``` also fails
* These packages are all in the engo_js.go file, suggesting something is up there

**Comment by bcokert** [comment]
Figured it out why it can't be downloaded by go get - The engo_js file is using build tags, I guess to divide by platform. This seems to cause go get to ignore its dependencies. Removing the build tag, my tools are successfully able to determine that those libs are now needed. This obviously isn't a solution though.

The proper fix is to download the sources for each other package as well - apparently downloading them all by default is not going to happen because of the nature of build tags (it could have anything in it) - https://github.com/golang/go/issues/4742.

Aka proper fix is:
```
go get -u -tags netgo ./...
go get -u -tags android ./...
```

I'll create a PR.

**Comment by bcokert** [comment]
https://github.com/EngoEngine/engo/pull/444

**Comment by otraore** [comment]
Fixed by: https://github.com/EngoEngine/engo/pull/444
