### ISSUE TITLE
App closing in Android

### ISSUE THREAD

**Issue by Noofbiz** [EngoEngine/engo#447]
Hello,

In android if you build a game, then close it using the home button, if you try to go back on the game using either the icon or the app switcher without force closing it first, the game crashes and won't reload until you force close it. It's due to the GL context not being destroyed on the app crossofff. I've got it worked out on my bransh so I'm submitting a PR for it.

Thanks!

**Comment by otraore** [comment]
Closed by https://github.com/EngoEngine/engo/pull/448
