### ISSUE TITLE
Animation: default

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#45]
The idea is that something has a user-defined default animation (i.e. standing still). 

Whenever someone wants to do something (i.e. animate a "grab", "jump", "kick", "nod", etc.), he calls a function and duration:
```go
something.Animate(ACTION_JUMP, time.Second * 0.5)
```
It animates as it normally would, but instead of repeating it, it would go back to animating the default behavior. 

Thoughts? @paked @matiwinnetou

**Comment by paked** [comment]
What if we added an extra field to the `Animation` call for looping. `Animation(id, time, loop) or something.

Also, when you add an `Animation` you should be able to set it as default.

**Comment by matiwinnetou** [comment]
Sounds like a good idea , I can try to prototype this.

I guess the usecase could be as follows as well:
character (our hero :+1: ) moves and then he jumps, we need to create new animation but instead of repeating this do this once, complete and proceed with character walking.

**Comment by paked** [comment]
I'm going to take a crack at this.
