### ISSUE TITLE
Question: Any simple way to drop CPU usage when nothing is changing? 

### ISSUE THREAD

**Issue by jrmiller82** [EngoEngine/engo#458]
I'm playing around with engo to see if it's suitable for my needs, and I have literally painted a single texture to the screen, added a KB scroller and a MouseZoomer, set the FPS limit to 60, and it's pegging all four cores of my i5 at 80%. There's no need to waste those CPU cycles (and battery of a laptop user) if the engine isn't doing any actual real work. I.e. no events have come in to act upon. 

Is there a way I'm missing to do this, other than with the limit FPS setting in RunOptions? Even dropping it down to 10 FPS leaves the CPU cores pegged at 50%.

**Comment by jrmiller82** [comment]
I owe you guys an apology. I think it was because I was running in a VM. I just ran it natively on a much lower spec'd laptop, and the 4 cores are less than 10% each.

**Comment by otraore** [comment]
Ok then, closing the issue.
