### ISSUE TITLE
Question: Is there a way to change scaling algorithms? 

### ISSUE THREAD

**Issue by jrmiller82** [EngoEngine/engo#460]
I'm wondering what scaling algorith engo is using to zoom in? nearest neighbor? bilinear? lanczos? I'm asking because zooming some textures look fairly jaggedy.

**Comment by Noofbiz** [comment]
Right now it's just the projection matrix multiplied by the view. Not very sophisticated, really. I think it would be useful to include other sharers that utilize better scale methods, but for now if you want it you'll just have to implement your own custom shader for this. 
A good place to see how to implement this would be here 
https://www.codeproject.com/Articles/236394/Bi-Cubic-and-Bi-Linear-Interpolation-with-GLSL#GLSLBiCubic

Remember though if you want to support mobile you'll need to write it compatible with OpenGl ES 2.0, and if you want support for web you'll need to be compatible with WebGl

**Comment by jrmiller82** [comment]
Got it. Thanks for your quick reply. 

Unfortunately, I likely lack the OpenGL knowledge to do that at this time. But, I'll give that article a read and see if it's something I can grok. (I don't know OpenGL well at all). 

So the current shader is just using GL_NEAREST interpolation?

**Comment by jrmiller82** [comment]
So that article says to switch from nearest neighbor to linear (which is likely a great first step to better inte rpolation) then the only needed shader code is: 

```
glTexParameteri( GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER, GL_LINEAR ); 
glTexParameteri( GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER, GL_LINEAR );
```

I'm taking a peak at render_shaders.go in common and trying to figure out where to add that in... and I just don't understand GLSL enough to figure out where that's going to go. 

Here's the current  `basicshader`:

```
s.program, err = LoadShader(`
attribute vec2 in_Position;
attribute vec2 in_TexCoords;
attribute vec4 in_Color;
uniform mat3 matrixProjection;
uniform mat3 matrixView;
uniform mat3 matrixModel;
varying vec4 var_Color;
varying vec2 var_TexCoords;
void main() {
  var_Color = in_Color;
  var_TexCoords = in_TexCoords;
  vec3 matr = matrixProjection * matrixView * matrixModel * vec3(in_Position, 1.0);
  gl_Position = vec4(matr.xy, 0, matr.z);
}
`, `
#ifdef GL_ES
#define LOWP lowp
precision mediump float;
#else
#define LOWP
#endif
varying vec4 var_Color;
varying vec2 var_TexCoords;
uniform sampler2D uf_Texture;
void main (void) {
  gl_FragColor = var_Color * texture2D(uf_Texture, var_TexCoords);
}`)
```

Thoughts?

**Comment by Noofbiz** [comment]
I think we should be able to implement some kind of option that we can use to pick from different scale algorithms. There's always a performance hit on higher level algorithms, and some games actually benefit best from nearest neighbor, such as pixel art based games.

**Comment by jrmiller82** [comment]
I completely understand that nearest neighbor is best for a game that is pixel art based. But, plain linear interpolation isn't *that* much of a performance hit and can make a big deal to more realistic textures that are upsized. 

I'm thinking that there should be something like a `TexturerInterpolation` variable in RunOptions that defaults to nearest neighbor if unset.

**Comment by Noofbiz** [comment]
Added in #519
