### ISSUE TITLE
There should be an option to hide the mouse cursor

### ISSUE THREAD

**Issue by dstewart** [EngoEngine/engo#465]
Something like `glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_HIDDEN)`

**Comment by dstewart** [comment]
Adding `glfw.GetCurrentContext().SetInputMode(glfw.CursorMode, glfw.CursorHidden)` in my Scene's Setup method seemed to do the trick

**Comment by dstewart** [comment]
This should be a member of RunOptions in my opinion, called CursorVisible or something along those lines. The above seems like a hack.

**Comment by jrmiller82** [comment]
Agreed, that should be in RunOptions. Should also have an Exportable func that lets the user switch it on the fly.

**Comment by otraore** [comment]
I agree, the thing is making sure it defaults to showing the mouse cursor. I think instead of having it in RunOptions and cluttering it, and not having to deal with booleans being defaulted to false, you can have methods on the package to handle it for each platform as applicable.

**Comment by Noofbiz** [comment]
I like the exportable function to hide/show at will. I'll add in for glfw and then try for gopherjs. Not familiar enough to know how to do it off the top of my head there, so it would take longer. Android/IOS obviously won't do anything with the function.
