### ISSUE TITLE
Some demos do not respond, when played by the browser. 

### ISSUE THREAD

**Issue by mragiadakos** [EngoEngine/engo#491]
Hi

When I started gopherjs to serve the demo games, I realized that some of them do not respond to the keyboard.
For example these two do not respond
http://localhost:8080/engo.io/engo/demos/adventure/
http://localhost:8080/engo.io/engo/demos/animation/

Also they didn't show any error message on the console.

However this demo responds.
http://localhost:8080/engo.io/engo/demos/pong/

I have Go's version go1.9 and GopherJS is 1.9-1 .
I tried it with Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by Noofbiz** [comment]
Happens for me too. Thanks for reporting this!

**Comment by Noofbiz** [comment]
The issue appears to be that ```engo.Input.Button(btn).JustPressed()``` is returning always returning false. The confusing thing is that adding ```fmt.Printf("At listener: %v\n", Input.keys.Get(A).JustPressed())``` below line 95 in engo_js.go is returning true even though it's returning false in adventure.go
