### ISSUE TITLE
Upgrade to glfw 3.3 when it's out of beta

### ISSUE THREAD

**Issue by Noofbiz** [EngoEngine/engo#531]
glfw 3.3 is at around 90% currently, and provides some nifty new features, such as support for vulkan (as well as molten for iOS and OSX) as well as Wayland, which Ubuntu is switching to from X.

**Comment by Noofbiz** [comment]
Alright, I'm going to have to implement Vulkan pretty soon, looks like macOS is depreciating openGL and it looks like there's plenty of stuff to get it going via [vulkan-go](https://github.com/vulkan-go/vulkan)

**Comment by hajimehoshi** [comment]
Nice, but doesn't this depend on MoltenVK, which is under commercial license?

**Comment by hajimehoshi** [comment]
Nvm, it looks like this is under Apache License 2.0

https://en.wikipedia.org/wiki/MoltenVK

**Comment by Noofbiz** [comment]
Yeah it originally was a commercial license but they've recently released an open source version
