### ISSUE TITLE
Parenting of BasicEntities or allow multiple RenderComponents for one BasicEntity

### ISSUE THREAD

**Issue by Noofbiz** [EngoEngine/engo#556]
Suggested by @juztme87

**Comment by juztme87** [comment]
Related to #555 
If one object has multiple sub objects all should be deleted once the parent is deleted.

**Comment by Noofbiz** [comment]
Thinking on this, couldn't it be solved simply by adding multiple SpaceComponents to a single entity just named differently? For example, for a tank we could have something like
```go
type TankEntity struct {
*ecs.BasicEntity
Base *SpaceComponent
Turret *SpaceComponent
Health *SpaceComponent
}
```

Then in your update just make sure the health / turret are properly offset from the base? I'll try to put together a gist for this that could showcase it better later. I'm just thinking that all space components wouldn't really need a reference to parents, and it could be handled the way it is now. Maybe there could be a demo or something added to the engo.io site showcasing something like this, because this isn't the first time someone's asked about this kind of functionality.

**Comment by juztme87** [comment]
That is how I did it before.
Works but has some flaws.
- Leads to duplicate code
- Its quite ugly on more complex objects If you have multiple BasicEntitys as well as SpaceComponents.

But maybe this can be resolved by a central Parenting System.
I will do some experiments and follow up with a proposal.

**Comment by yarbelk** [comment]
Different use case What happens if what you want is different ways of rendering something based on what/how or where you're rendering.

Something i've always wanted to do was have different renders based on what 'sensors' you have (eg; for a sim game; if I use sonar vs sight vs radar)

Sometimes you what a mix of multiple so same space component, but different render component.

**Comment by jonbonazza** [comment]
I think implementing a hierarchical relationship between nodes would be an excellent addition. Take a simple player entity as an example. Some games might have multiple components to a "player" entity--a head, a body, a weapon, etc... It would be nice if we could just update the position of the root entity and all of the children are updated in relation to that root entity. This is how most game engines work.

**Comment by Noofbiz** [comment]
Closed in https://github.com/EngoEngine/ecs/pull/35
