### ISSUE TITLE
engo.Point methods return the point

### ISSUE THREAD

**Issue by Noofbiz** [EngoEngine/engo#559]
engo.Point methods could return an engo.Point, so you can chain together multiple calls:

```go
p1 := engo.Point{X: 5, Y:5}
p2 := engo.Point{X: 2, Y:3}
p1.Add(p2).MultiplyScalar(2).Normalize()
```

**Comment by jeet-parekh** [comment]
Seems like a good first issue. Is it still just a proposal? I'd like to give it a shot, if you're not working on it @Noofbiz.
