### ISSUE TITLE
Click handling

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#59]
How should clicks be handled according to the ECS?

In `javascript`/`html`, there's some kind of propagation: the foremost element is clicked, then passed along to any other element that may have been involved ; and each time the element has the ability to stop the propagation. 

In ECS, I would assume there is some kind of `System` that monitors whether or not something gets clicked? 

Any best-practices here? Anything I misunderstood? (I imagine the "buttons" in the "main menu" I'm creating, to be some kind of clickable)

---------------------

## Current status

* [ ] Rightclick-handling

**Comment by paked** [comment]
AFAIK there is no "Clicking Idiom" in ECS. @matiwinnetou correct me if I am wrong.

Clicking is something we desperately need though, I am a big fan of the propagation model from `javascript/html` though.

Would you mind if I took this PR?

**Comment by EtienneBruines** [comment]
Be my guest.

**Comment by paked** [comment]
@EtienneBruines what are your thoughts on implementing this handler at the `World` level?

**Comment by EtienneBruines** [comment]
A `ClickSystem`, together with `ClickComponent`s. 

If an `Entity` has a `ClickComponent`, the `ClickSystem` will use the `SpaceComponent` and `Mouse` values to see if it's being clicked, and if so, either set some value at `ClickComponent` to `CLICKED`, or perhaps dispatch some `Message`?

**Comment by paked** [comment]
@EtienneBruines I think implementing this as a `System` is a good idea. Although, if we do this we may as well remodel the way key input works as well.

I believe going with the messaging model for this would serve us best.

**Comment by EtienneBruines** [comment]
Well, with keys the state is kinda important: just clicked, holded, released, etc. And combinations of keys. 

A `click` is simply a `click`.

**Comment by paked** [comment]
@EtienneBruines state can actually be important for `click`s too.

Imagine a button: You want to act when the button has been released!

Imagine a shooting game: You want to act when the button is first pressed, and perhaps when it is continuously held down.

===

Either way however, this is irrelevant (for both clicks and key presses). Data can be transferred within a message.

[For example](https://github.com/paked/engi/blob/master/demos/pong/pong.go#L233-L248)
```go
engi.Mailbox.Listen("ScoreMessage", func(message engi.Message) {
	scoreMessage, isScore := message.(ScoreMessage)
	if !isScore {
		return
	}

	sc.scoreLock.Lock()
	if scoreMessage.Player != 1 {
		sc.PlayerOneScore += 1
	} else {
		sc.PlayerTwoScore += 1
	}

	log.Println("The score is now", sc.PlayerOneScore, "vs", sc.PlayerTwoScore)

	sc.upToDate = false
	sc.scoreLock.Unlock()
})
```

**Comment by EtienneBruines** [comment]
Good point. Messages are kinda cheap anyway, so we could do that, yes.

**Comment by paked** [comment]
Thoughts @matiwinnetou?

**Comment by EtienneBruines** [comment]
(We should also note that this should indeed also cover things like `hover`)

**Comment by EtienneBruines** [comment]
Have you already started working on this, or can I create something with a `ClickSystem` and `ClickComponent`, which has some states (i.e. `Clicked`, `Hovered`, `Focused`, etc.)?

(I'm making a little game, and am in need of this; don't want to rush you, but also don't want to wait if you don't have time for it anyway; again: **I do not mean this in a negative way**, whatsoever. :smile:  )

**Comment by paked** [comment]
@EtienneBruines feel free to take this.

**Comment by EtienneBruines** [comment]
Tricky; currently at "how to handle zooming", and "how to handle scrolling to the sides". 

The very basics work.

**Comment by paked** [comment]
:+1:

**Comment by EtienneBruines** [comment]
Current status:

#TODO
* [ ] Rightclick.

**Comment by paked** [comment]
@faide If you want to take a crack at this, I'd be happy to review the pull request!

**Comment by faide** [comment]
@paked I did first run here: #146

**Comment by paked** [comment]
Correct me if I'm wrong, but #146 fixed this.
