### ISSUE TITLE
Gopherjs does not play audio

### ISSUE THREAD

**Issue by Noofbiz** [EngoEngine/engo#596]
Due to changes with oto and wasm as well as chrome requiring user input before playing, audio is not playing (at least on Safari and Chrome).

**Comment by hajimehoshi** [comment]
Note that even without Oto's fix, Chrome 71 (December 2018) will require user-interaction to play audio anyway.

**Comment by Noofbiz** [comment]
Yeah the issue is that vanilla js can only hold one callback per event so when oto adds the event it gets overwritten by engo's listeners and never starts the player. The easiest fix would be to switch over to gopherjs/wasm

**Comment by Noofbiz** [comment]
Yeah it uses gopherjs/wasm/js to add the listener. Currently engo uses honnef.co/dom objects to do it which is what I'm guessing is the difference. I need to research more to see.

**Comment by hajimehoshi** [comment]
Sure, thank you for elaborating :-)
