### ISSUE TITLE
EntityScroller nil pointer safety

### ISSUE THREAD

**Issue by juztme87** [EngoEngine/engo#610]
If EntityScroller is added without a SpaceComponent set, a nil pointer exception will occur on first update.

Possible fix in Update method:
```go
if c.SpaceComponent == nil{
  return
}
```

**Comment by Noofbiz** [comment]
Is there a use case where you'd want an EntityScroller without an entity? To me this failing would point to a mistake that needs to be fixed by the user, not something that should be handled. Wouldn't that just make that bug harder to track down?

**Comment by juztme87** [comment]
Use Case 1:
I add EntityScroller during Scene Setup.
The Player Entity is later added through a Spawn System.

Use Case 2:
Optional Entity Following.
For example you have multiple entities moving on the map and by default you can scroll via EdgeScroller.
If you click an entity EntityScroller is configured to follow its SpaceComponent.
If you click somewhere else the SpaceComponent of EntityScroller is set to nil and EdgeScroller is used.
In this case an enable/disable flag would be good for all Scrollers as well (or maybe the solution for this issue in general).
