### ISSUE TITLE
Mobile (+ tablet) support

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engo#63]
We'd like to support `engi` on Android and iOS. 

List of thoughts:

* We would need OpenGL / GLFW available on the mobile device; or refactor a lot
* We would want to support both phones and tablets
* Mobile support should improve in Go 1.6. 

Any additional information can be posted in this issue. 

# Todo list
(will be added upon when needed)

* [x] Add within `webgl` a compatibility-layer for https://godoc.org/golang.org/x/mobile/gl
* [x] Add within `engo`, w.r.t. the `OpenWindow`, `RunIteration`, `runLoop` functions, a compatibility-layer for https://godoc.org/golang.org/x/mobile/app (Compare https://github.com/EngoEngine/engo/blob/gopherjs/engo_netgo.go with https://github.com/EngoEngine/engo/blob/gopherjs/engo_glfw.go for a general idea on what's needed,

**Comment by matiwinnetou** [comment]
+1 killer feature and would make engi professional not a toy project. Games on mobile are a reality since companies and individuals can earn serious money with this.

**Comment by paked** [comment]
@matiwinnetou would you be interested in heading up this development?

**Comment by matiwinnetou** [comment]
@paked no this is at the moment too big for what I can afford to this project. :(

**Comment by lovoror** [comment]
Great!

**Comment by EtienneBruines** [comment]
See https://github.com/EngoEngine/engo/pull/274 - almost done with this issue.

**Comment by paked** [comment]
🎉
