### ISSUE TITLE
Update audio to use newest version of oto

### ISSUE THREAD

**Issue by Noofbiz** [EngoEngine/engo#638]

**Comment by Noofbiz** [comment]
Fixed by #720

**Comment by hajimehoshi** [comment]
Another fix was to have go.mod to use old Oto. Having go.mod would be nice to prevent similar issues of breaking changes in dependencies anyway :-)

**Comment by otraore** [comment]
@hajimehoshi You're totally right, but there's no reason for us to not receive new improvements/bug fixes by locking ourselves to an old version when we can just make a minor API change for something that's been deprecated for over a year.
