### ISSUE TITLE
Update go mod and test on go 1.12

### ISSUE THREAD

**Issue by Noofbiz** [EngoEngine/engo#660]

**Comment by Noofbiz** [comment]
Looks like gopherjs doesn't work anymore? I get panics saying it requires go 1.11

**Comment by hajimehoshi** [comment]
Yes and I plan to work on making this support Go 1.12 https://github.com/gopherjs/gopherjs/issues/887

**Comment by Noofbiz** [comment]
Everything else works with 1.12 so I'm going to close this and open another issue to track gopherjs
