### ISSUE TITLE
error on win10

### ISSUE THREAD

**Issue by akifai** [EngoEngine/engo#676]
C:\Users\u7658>go get -u github.com/EngoEngine/engo
# github.com/go-gl/glfw/v3.2/glfw
exec: "gcc": executable file not found in %PATH%
# github.com/go-gl/gl/v2.1/gl
exec: "gcc": executable file not found in %PATH%

**Comment by Noofbiz** [comment]
It looks like you don't have a gcc toolchain on your path. I recommend using something like [mingw](http://mingw-w64.org/doku.php/start) to get it. [Win-builds](http://win-builds.org/doku.php) also looks promising and has a nice GUI to install packages, I would try that out.
