### ISSUE TITLE
Can't go get on MacOS 10.14

### ISSUE THREAD

**Issue by dtldyg** [EngoEngine/engo#677]
$ go get -u github.com/EngoEngine/engo
# github.com/Noofbiz/glfwMojaveFix
Documents/go-common/src/github.com/Noofbiz/glfwMojaveFix/fix_cocoa.go:10:5: warning: 'NSOpenGLContext' is deprecated: first deprecated in macOS 10.14 - Please use Metal or MetalKit. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGL.h:202:12: note: 'NSOpenGLContext' has been explicitly marked deprecated here

**Comment by Noofbiz** [comment]
Yeah, this depreciation notice happens whenever you try to compile glfw on Mojave. It shouldn't stop it from building, using or getting the library. It just means that osx is depreciating OpenGL in favor of Metal. I'm working on a Vulkan rendering system that will work for this. In the meantime, just ignore the warnings.

**Comment by dtldyg** [comment]
> Yeah, this depreciation notice happens whenever you try to compile glfw on Mojave. It shouldn't stop it from building, using or getting the library. It just means that osx is depreciating OpenGL in favor of Metal. I'm working on a Vulkan rendering system that will work for this. In the meantime, just ignore the warnings.

At first I tried to get engo to my gopath with go get, but it was interrupted when the warning appeared.
Now I compile directly with go mod, as you said, it didn't stop my compile and finally the program runs successfully. Now I can write code happily. :)
