### ISSUE TITLE
WASM build doesn't work

### ISSUE THREAD

**Issue by Noofbiz** [EngoEngine/engo#697]
due to changes regarding array allocation in go and js, our build using go1.13 is broken. We need to fix it in EngoEngine/gl as well.

**Comment by hajimehoshi** [comment]
Note that go1.14 includes further breaking change :-) (js.Value is no longer comparable)

**Comment by Noofbiz** [comment]
Yeah, I suppose that's what happens when you try to support stuff when the api can still change :P

**Comment by Noofbiz** [comment]
Closed by #701
