### ISSUE TITLE
Possibly replace appveyor and travis with GitHub actions

### ISSUE THREAD

**Issue by Noofbiz** [EngoEngine/engo#710]
Look into this. Currently Travis CI is the biggest issue due to constant API changes and even the site has a .com and .org with different apis boo. Also maybe it can do windows and Linux in one

**Comment by hajimehoshi** [comment]
Interesting. I've not succeeded to run GLFW application on GitHub Actions yet. Good luck!

**Comment by Noofbiz** [comment]
Closed by #711
