### ISSUE TITLE
undefined: oto.NewPlayer

### ISSUE THREAD

**Issue by waltrapa** [EngoEngine/engo#719]
$ go version
go version go1.14.3 linux/amd64

At try to build https://github.com/EngoEngine/engo/tree/master/demos/hello-world fail:
$ go build hello.go 
$# github.com/EngoEngine/engo/common
../../../src/github.com/EngoEngine/engo/common/audio.go:93:21: undefined: oto.NewPlayer

oto example https://github.com/hajimehoshi/oto/blob/master/example/main.go build and run perfect.

**Comment by Asday** [comment]
https://github.com/hajimehoshi/oto/issues/76

**Comment by otraore** [comment]
Fixed via #720. Thanks for bringing attention to the issue! Let us know if you're still having any issues.
