### ISSUE TITLE
undefined: oto.newPlayer

### ISSUE THREAD

**Issue by LsHallo** [EngoEngine/engo#724]
```
# github.com/EngoEngine/engo/common
..\..\EngoEngine\engo\common\audio.go:90:22: undefined: oto.NewPlayer
```

I'm new to the whole go thing and I was just installing engo and testing the pong sample. For that I created src in $GOPATH and hello.go (just fmt.printLn('Hello')) works fine. Then I went on to test the pong demo and I got a whole bunch of missing x. Then I used go get in the dir of the pong demo and now I have the above error.

Platform: Windows 10 mingw64

Also made sure to run git checkout v1.0.4 in engo and v1.0.3 in ecs

**Comment by Noofbiz** [comment]
Try `go get @master` to fix it. The previous versions use an earlier version of oto, hence the issues. Not sure why go mod doesn't just use the right version of oto like it's supposed to though xD.

**Comment by LsHallo** [comment]
That seems to have fixed it. Thanks!
