### ISSUE TITLE
Determine the screen resolution of an application

### ISSUE THREAD

**Issue by tetravalence** [EngoEngine/engo#745]
Hello, I'm sorry for this silly question but I'd like to know if I should determine the screen resolution of the desktop (for example running in Xorg) before to call `engo.Run` function and then set `RunOptions` appropriately instead of using fixed constants `Width` and `Height` when the game is to be run in window mode or is this procedure a bad coding practice to avoid?

**Comment by Noofbiz** [comment]
Hello! If you need the information about the monitor before calling `engo.Run` you can get it through GLFW. Here's the glfw monitor [guide](https://www.glfw.org/docs/latest/monitor.html). You'd use the width and height of the monitor's VideoMode.

**Comment by tetravalence** [comment]
OK thank you very much!
