### ISSUE TITLE
Circle fill transparency

### ISSUE THREAD

**Issue by kayon** [EngoEngine/engo#766]
I've seen changes, But new problems are coming.
When the fill color has transparency, it looks like this.
<img width="138" alt="01" src="https://user-images.githubusercontent.com/5260178/110074386-18e64580-7dbc-11eb-82f4-8a5945d95c2e.png">

**Comment by eth0net** [comment]
How are you setting transparency? It's working for me using the following code:

```go
rectangle := MyShape{BasicEntity: ecs.NewBasic()}
rectangle.SpaceComponent = common.SpaceComponent{Position: engo.Point{100, 100}, Width: 50, Height: 50}
rectangle.RenderComponent = common.RenderComponent{Drawable: common.Rectangle{}, Color: color.RGBA{0, 255, 0, 255}}

circle := MyShape{BasicEntity: ecs.NewBasic()}
circle.SpaceComponent = common.SpaceComponent{Position: engo.Point{100, 100}, Width: 50, Height: 50}
circle.RenderComponent = common.RenderComponent{Drawable: common.Circle{BorderWidth: 1, BorderColor: color.White}, Color: color.Transparent}
```

**Comment by kayon** [comment]
When the fill color has transparency.
<img width="125" alt="01" src="https://user-images.githubusercontent.com/5260178/110102435-bdc64a00-7ddf-11eb-9578-1333d8e3b804.png">

`
common.RenderComponent{Drawable: common.Circle{}, Color: color.NRGBA{R:0, G:0xFF, B:0, A:0xA0}}
`

**Comment by kayon** [comment]
When the fill color has transparency, It's not about borders.
<img width="129" alt="01" src="https://user-images.githubusercontent.com/5260178/110102910-48a74480-7de0-11eb-8644-2d4ab66705bd.png">
`
common.RenderComponent{Drawable: common.Circle{}, Color: color.RGBA{R:0xFF, G:0, B:0, A:0xA0}}
`

**Comment by kayon** [comment]
<img width="131" alt="01" src="https://user-images.githubusercontent.com/5260178/110111821-df2d3300-7deb-11eb-94db-71bacbbb77f1.png">

`common.Circle{Arc: 180}`


```
theta := float32(2.0*math.Pi/355.0) * shape.Arc / 360

fmt.Println(2.0*math.Pi/355.0*180/360)
fmt.Println(float32(2.0*math.Pi/355.0*180/360))
// output
// 0.008849556770675475
// 0.008849557
```

And this, float32 losing precision.

**Comment by eth0net** [comment]
My point with my code was that I'm using color.Transparent for the circle fill color and it works, the border was only there to show the location of the transparent circle.

Unfortunately I'll have to leave the circle maths to @Noofbiz for the time being, until I've figured that out.

**Comment by Noofbiz** [comment]
Hello! Thanks for looking into this so well. It really helps us improve things! Check out #767 and let me know if that helps ^_^

**Comment by Noofbiz** [comment]
Oh and I kind of missed it until now, to add support for Chinese characters you need to set 'common.UnicodeCap' to a high enough value
