### ISSUE TITLE
Support WebGL and Android

### ISSUE THREAD

**Issue by zurgeg** [EngoEngine/engo#775]
Currently, Engo uses `github.com/go-gl/gl`, which limits us to `darwin`, `windows`, and `linux` (and `freebsd` iirc). Engo should switch to a more cross-platform GL port. I propose the usage of https://github.com/goxjs/gl.

**Comment by Noofbiz** [comment]
Actually, engo uses 'github.com/EngoEngine/gl` which has support for mobile and web!

**Comment by zurgeg** [comment]
> 
> 
> Actually, engo uses `github.com/EngoEngine/gl` which has support for mobile and web!

Huh, I tried to build for Web and it failed

**Comment by Noofbiz** [comment]
I currently use https://github.com/Noofbiz/engoWasmServer as an automated tool for testing myself, but all it uses is the normal go tools with goos=js and goarch=wasm to build. If you need more help building for us let me know, I’ll keep this open.

**Comment by zurgeg** [comment]
> 
> 
> I currently use https://github.com/Noofbiz/engoWasmServer as an automated tool for testing myself, but all it uses is the normal go tools with goos=js and goarch=wasm to build. If you need more help building for us let me know, I’ll keep this open.

Alright, I will grab the error later, right now my terminal is closed and I'm too lazy to open it :P

**Comment by zurgeg** [comment]
@Noofbiz After further research, I get `src/github.com/EngoEngine/gl/gl_webgl.go:1541:2: undefined: log.Error` when attempting to build EngoEngine/gl, rather then a constraint related error like I got before, but still an error. Any idea why this happens?

**Comment by Noofbiz** [comment]
I updated to use the latest gl, should take care of that error message

**Comment by zurgeg** [comment]
> 
> 
> I updated to use the latest gl, should take care of that error message

Great, I will try building, glad I could find a bug ^^)

**Comment by zurgeg** [comment]
@Noofbiz Now it fails with:
```
/home/redacted/go/src/github.com/EngoEngine/engo/engo_js.go:46:25: document.Get("body").IsNull undefined (type js.Value has no field or method IsNull)
/home/redacted/go/src/github.com/EngoEngine/engo/engo_js.go:172:9: joy.IsNull undefined (type js.Value has no field or method IsNull)
/home/redacted/go/src/github.com/EngoEngine/engo/engo_js.go:188:9: joy.IsNull undefined (type js.Value has no field or method IsNull)
/home/redacted/go/src/github.com/EngoEngine/engo/gamepads_js.go:32:19: gpds.Index(i).IsNull undefined (type js.Value has no field or method IsNull)
/home/redacted/go/src/github.com/EngoEngine/engo/gamepads_js.go:54:11: window.IsUndefined undefined (type js.Value has no field or method IsUndefined)
/home/redacted/go/src/github.com/EngoEngine/engo/gamepads_js.go:54:52: window.Get("navigator").IsUndefined undefined (type js.Value has no field or method IsUndefined)
/home/redacted/go/src/github.com/EngoEngine/engo/gamepads_js.go:66:20: gpds.Index(i).IsNull undefined (type js.Value has no field or method IsNull)

**Comment by zurgeg** [comment]
@Noofbiz Turns out that [on some versions of Go](https://github.com/hajimehoshi/oto/commit/0644fbe4140cab93ffb80332978e292f2676c1fe), you need to use `ValueEqual`. Build fails with this error for reference:
```
engo_js.go:45:26: invalid operation: document.Get("body") == js.Null() (struct containing [0]func() cannot be compared)
```

**Comment by zurgeg** [comment]
Oh wait, turns out my version of Engo was outdated haha, will try building once I fix that

**Comment by zurgeg** [comment]
Can confirm, it works now
