### ISSUE TITLE
Release v1.0.7 appears to be tagged incorrectly

### ISSUE THREAD

**Issue by hansnqyr** [EngoEngine/engo#792]
Hi, the tag for release 1.0.7 is a bit inconsistent compared to previous releases.
It's tagged as `1.07` which both drops the v and drops the minor/patch separator.

This isn't a blocking issue as using `"1.07"` in go mod works fine, but it did catch me out when trying to upgrade as the release is labelled `v1.0.7`

**Comment by Noofbiz** [comment]
I couldn't figure out how to update it, so I just made a new release that goes with the previous convention. Thanks for catching that!
